### ISSUE TITLE
Not compatible with format3 of Glyphs app 

### ISSUE THREAD

**Issue by shiyangehe878** [googlefonts/glyphsLib#1001]
When I am trying to use glyphs2ufo on `format3` files, it reports this error
```
AttributeError: 'str' object has no attribute '_parent'
```
Then I tried to use a `format2`file. It works perfectly.

**Comment by schriftgestalt** [comment]
The support for Glyphs 3 files is almost finished (you can check the Glyphs3 branch).

**Comment by shiyangehe878** [comment]
Do I need to reinstall the glyphsLib or download the brand and drag it to the glyphs2ufo dir?

**Comment by schriftgestalt** [comment]
the easiest is to clone the git repo, switch to the "Glyphs3_Merge" branch, open the repo folder in Terminal and do `pip3 -e .` that installs glyphsLib into the current python. You might need to do `pip3 uninstall glyphsLib` first to remove the previous version.

**Comment by shiyangehe878** [comment]
Thank you! It's all done!
