### ISSUE TITLE
new propagate_anchors may produce an infinite loop with cyclical component references

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/glyphsLib#1022]
if two composite glyphs reference each other, the new propagate_anchors code may enter an infinte loop (inside `depth_sorted_composite_glyphs` function).

Normally cyclical component references are flagged with a "bad reference" icon in Glyphs.app, so they don't occur in real-world fonts.

However a cycle could still happen if a glyph contains a backup layer that points to some glyph, and this in turn points back to the glyph containing such backup layer.
This happen with https://github.com/googlefonts/genos, where 'caroncomb' contains a backup layer with a 'caron' component, and the 'caron' glyph's (master) layers contain a 'caroncomb' component.
Our `depth_sorted_composite_glyphs` has a `while queue` loop that never ends because the same glyphs keeps being added and popped forever.

Note this is not actually a cycle for Glyphs.app because the backup layer itself (being unique to its parent glyph) is actually dereferencing to the associated master layer from the base glyph (which in turn references a different base glyph and as such is not flagged as a "bad reference" in the UI).

the infinite loop doesn't trigger with fontc but that's just because fontc only loops over the master layers, the backup layers are pruned beforehand. It would similarly loop forever if it encounters a 'bad reference' in one of those master layers (which is unlikely in real world fonts as I said).

**Comment by schriftgestalt** [comment]
When propagating anchor (or paths), I always have one  argument that is a set of the glyph names that were seen already in the propagation.
