### ISSUE TITLE
Merging of kerningLTR and kerningRTL drops kerns

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/glyphsLib#1039]
The attached Glyphs file ([PlaypenSans-mini.glyphs.gz](https://github.com/user-attachments/files/17578383/PlaypenSans-mini.glyphs.gz)) contains a LTR kern table:

```
kerningLTR = {
"5FC9277C-B92C-4C3C-88AB-70E16AEC7C11" = {
"@MMK_L_A" = {
"@MMK_R_quotesingle" = -49;
};
"@MMK_L_quotesingle" = {
"@MMK_R_A" = -49;
"@MMK_R_space" = -20;
};
"@MMK_L_space" = {
"@MMK_R_quotesingle" = -20;
};
};
};
```

and an RTL kern table:

```
kerningRTL = {
"5FC9277C-B92C-4C3C-88AB-70E16AEC7C11" = {
"@MMK_R_bet-hb" = {
"@MMK_L_quotesingle" = -30;
};
"@MMK_R_quotesingle" = {
"@MMK_L_bet-hb" = -20;
};
"@MMK_R_vav-hb" = {
"@MMK_L_bet-hb" = 16;
};
};
};
```

When processed with `glyphs2ufo` (or fontmake) the resulting `kerning.plist` is:

```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>public.kern1.A</key>
    <dict>
      <key>public.kern2.quotesingle</key>
      <integer>-49</integer>
    </dict>
    <key>public.kern1.bet-hb</key>
    <dict>
      <key>public.kern2.quotesingle</key>
      <integer>-30</integer>
    </dict>
    <key>public.kern1.quotesingle</key>
    <dict>
      <key>public.kern2.bet-hb</key>
      <integer>-20</integer>
    </dict>
    <key>public.kern1.space</key>
    <dict>
      <key>public.kern2.quotesingle</key>
      <integer>-20</integer>
    </dict>
    <key>public.kern1.vav-hb</key>
    <dict>
      <key>public.kern2.bet-hb</key>
      <integer>16</integer>
    </dict>
  </dict>
</plist>
```

Notice that while `A quotesingle -49` appears in the UFO, `quotesingle A -49` has been dropped.

**Comment by anthrotype** [comment]
ouch.
it must be happening here where the flipped kern1 is inserted in the combined_kerning dict:
https://github.com/googlefonts/glyphsLib/blob/1cb4fc5ae2cf385df95d2b7768e7ab4eb60a5ac3/Lib/glyphsLib/builder/kerning.py#L44-L48

what's the expected behavior in this particular case? That both the LTR and RTL kern2s get merged into the exsiting kern1.quotesingle?

```diff
     <key>public.kern1.quotesingle</key>
     <dict>
       <key>public.kern2.bet-hb</key>
       <integer>-20</integer>
+      <key>public.kern2.A</key>
+      <integer>-49</integer>
+      <key>public.kern2.space</key>
+      <integer>-20</integer>
     </dict>
```

**Comment by simoncozens** [comment]
Right, that's the only correct behaviour, otherwise we drop kerns.

**Comment by anthrotype** [comment]
there's still a change of conflicts/dropped kerns when both LTR and RTL dicts define the same (swapped) kerns, in that case what we should do?

**Comment by anthrotype** [comment]
I have a patch and will send a PR soon

**Comment by simoncozens** [comment]
> there's still a chance of conflicts/dropped kerns when both LTR and RTL dicts define the same (swapped) kerns, in that case what we should do?

This would only make sense for two Common script glyphs, and only if the same pair has different kerning values in LTR and RTL. Probably best just to warn because (a) we can't support it and (b) it's almost certainly a mistake.
