### ISSUE TITLE
Point identifiers/names from Glyphs to UFO?

### ISSUE THREAD

**Issue by jenskutilek** [googlefonts/glyphsLib#1049]
Is it possible to add some data in a Glyphs file so that it ends up as names/identifiers of points in the UFOs?

I've set GSNode.name in the Glyphs file, but the names don't make it to the UFO at all.

There is nothing in GSNode that seems to be corresponding to a UFO point identifier.

Following the spec, I would need more of an identifier than a name in the UFO. Identifiers are unique per glyph, and should not change when the outline is processed.

**Comment by jenskutilek** [comment]
This is weird, a point's name will be taken from GSNode.userData, even though I think it should be taken from GSNode.name directly:

https://github.com/googlefonts/glyphsLib/blob/74c63244fdbef1da540d646b0784ae6d2c3ca834/Lib/glyphsLib/builder/paths.py#L50-L61

Would it be desirable to add an `identifier` entry to GSNode.userData which will be transferred by glyphsLib as well?

**Comment by schriftgestalt** [comment]
I just had a look what Glyphs would do with the `point.identifer`. And it turned out it would ignore it. I fix that. So it is now stored in `node.userData["UFO.identifier"]`.
