### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by schriftgestalt** [googlefonts/glyphsLib#137]
This is more an observation than an issue. I found that when building an .ufo, more than half the time is spend in `postNotification()` of the defcon objects. Maybe you find a way to disable it when not needed (only post the notification when there is at least one observer??).

**Comment by anthrotype** [comment]
yep, that's a known issue:
https://github.com/typesupply/defcon/issues/79#issuecomment-239960319

**Comment by madig** [comment]
We use ufoLib2 by default, so this is solved.
