### ISSUE TITLE
Custom parameter "Link Metrics With Master" support is not complete

### ISSUE THREAD

**Issue by jenskutilek** [googlefonts/glyphsLib#256]
Presence of "Link Metrics With Master" or "Link Metrics With First Master" means that the masters that have set this custom parameter must also inherit the kerning from the referenced master.

At the moment, using this parameter results in the dependent UFOs/fonts having no kerning at all.

**Comment by anthrotype** [comment]
Support for that is non-existent rather than incomplete. I didn't know it existed before. Thanks anyway :)
