### ISSUE TITLE
use `fileName` custom parameter for generated master UFOs?

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/glyphsLib#319]
we read `fileName` custom parameter when generating _instance_ UFOs:
https://github.com/googlei18n/glyphsLib/pull/217

but for the _master_ UFOs we don't. We simply concatenate family and style names:

https://github.com/googlei18n/glyphsLib/blob/95e8b44d996dcf3f39df30e8ffd198848eeef333/Lib/glyphsLib/util.py#L23-L36

Can masters have a ~~`familyName`~~`fileName` custom parameter in Glyphs.app?

I guess they can't, because one can't save/export a master as a standalone UFO or TTF from Glyphs.app, only instances can... :thinking:

**Comment by anthrotype** [comment]
EDIT: sorry, I meant `fileName`, not `familyName`

**Comment by belluzj** [comment]
I don't know about such a parameter, and currently for round-tripping I'm storing this in the master's userData, but I would be happy to change to a custom parameter:

https://github.com/belluzj/glyphsLib/blob/e5730bc2696111b92f7efdbc149bcf2c7d32b4f7/Lib/glyphsLib/builder/sources.py#L48-L49

**Comment by moyogo** [comment]
Since in Glyphs that custom parameter doesn't exist and doesn't make sense for masters, you should use Jany’s UFO_FILENAME_KEY. Unless Glyphs starts exporting UFOs+designspace and using `filename`for masters.

**Comment by schriftgestalt** [comment]
> Unless Glyphs starts exporting UFOs+designspace and using filenamefor masters.

I’m thinking about building a plugin that uses glyphsLib and friends to export designspace+ufo. That would be a very good test case for the API.

**Comment by madig** [comment]
I think I will introduce a new custom parameter "UFO Filename" for both masters and instances, which will carry the filename of the master UFO or instance relative to the resulting Designspace file.

Currently, this information is split into `master.userData` key `com.schriftgestaltung.Glyphs.ufoFilename` and the instance's custom parameter `com.schriftgestaltung.Glyphs.fullFilename`. We sometimes run into the problem that people duplicate masters but don't know about the master's userData, so glyphs2ufo then fails with an AssertionError somewhere when two master filenames are the same.

**Comment by schriftgestalt** [comment]
Sounds good.
