### ISSUE TITLE
Support Replace Prefix custom parameter

### ISSUE THREAD

**Issue by punchcutter** [googlefonts/glyphsLib#529]
This is mentioned somewhat in https://github.com/googlefonts/glyphsLib/issues/506 and https://github.com/googlefonts/glyphsLib/issues/253 and in some fontmake issues, but to fully support including external feature files the way Glyphs does we need to read this parameter. We have external files defined with `Replace Prefix` for each instance.

**Comment by madig** [comment]
Out of curiosity, which/what kind of instance-specific data are you trying to insert?

**Comment by anthrotype** [comment]
Thanks @punchcutter for the reminder.
So, this "Replace Prefix" custom parameter only works for instances, right? Not for masters.
If that's the case, I believe this approach of swapping features "prefixes" won't work when generating a variable font from the same source file. But perhaps that's ok if the source is only meant to be exported as static instances.

**Comment by schriftgestalt** [comment]
Yes. This parameter only works for static instances. 

How to control details for variable fonts is to be seen. If someone has a good suggestion...

**Comment by punchcutter** [comment]
What we have right now has chained contextual GSUB with different rules based on each master weight. Then all 36 instances point to one of those. Each one is hundreds of lines so although It's possible to keep it all inside the Glyphs file it's a little easier to handle as separate files. Since it's Noto it will go through the fontmake pipeline so we need to make sure this will work or we will have to rework the file.

**Comment by anthrotype** [comment]
is this Noto source file going to be used to build a variable font as well as static instances, or only the latter?

**Comment by punchcutter** [comment]
Uh oh. I forgot the Noto pipeline now makes variable fonts out of everything. Nothing in Noto was designed to be a variable font originally. They just have multiple weights so for the most part it's possible to make them variable. In that case these include statements aren't going to work.

**Comment by anthrotype** [comment]
I see. Can I also ask what Noto font specifically this is about?

**Comment by punchcutter** [comment]
It's Noto Serif Devanagari.

**Comment by punchcutter** [comment]
Looking at this more there are a couple ways a Glyphs Prefix can be used
- Point to an external feature file with `include()`
- Hold lookups that can be referred to in contextual lookups written inside each feature

Originally I was only thinking of the first one, but to consolidate the external code I moved it into the Prefix. That way using Replace Prefix will replace the entire code block instead of only replacing an `include` statement.

**Comment by anthrotype** [comment]
> chained contextual GSUB with different rules based on each master weight.

@punchcutter I wonder, why does GSUB have to differ across masters in Noto Serif Devanagari? I understand for GPOS you may need different positioning values for different designs, but why should the substitution logic be different? Isn't it the same glyph set, just bolder/narrower?

**Comment by punchcutter** [comment]
Ideally the GSUB is the same across masters, but not necessarily. I think that mostly happens for more complex situations like when 3 or 4 glyphs combine in some way and a vowel or subscript form needs to swing over or under all or part of it. I think Noto Myanmar Sans or Serif also has something different between weights in the GSUB.
