### ISSUE TITLE
Spurious notes with glyph name attached to glyphs

### ISSUE THREAD

**Issue by madig** [googlefonts/glyphsLib#542]
This is a weird one. At work and in Cantarell, I noticed that a lot of glyphs have a note element attached to them that simply carries the glyph name. A quick inspection of the code and roundtripping of a fresh UFO shows no such notes so I'm not sure where they are coming from. Investigate.

**Comment by schriftgestalt** [comment]
Glyphs sometimes does this when importing fonts and converting glyph name. The original name is stored in the note.

**Comment by madig** [comment]
Mystery solved I guess.

Does "importing" also encompass opening `.glyphs` files?

**Comment by belluzj** [comment]
> Glyphs sometimes does this when importing fonts and converting glyph name. The original name is stored in the note.

Would it be possible to store that information in the userData for example?

**Comment by schriftgestalt** [comment]
This should only happen when opening .otf or maybe .ufos. 

The point was to put it in a place where the user can see it (with the GlyphNote plugin, or in list view).
