### ISSUE TITLE
zeroing combining marks advances from right-hand side?

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/glyphsLib#547]
when glyphsLib exports combining mark glyphs (category "Mark", subCategory "Nonspacing") it simply sets their advance width to 0.

However, I just noticed that Glyphs.app not only sets their advance to 0, but it also _shifts_ their outlines to the ~~right~~ left by an amount equal to their advance width, so that the original right-side bearing is maintained.

@schriftgestalt can you confirm this?

I wonder if we need to do the same.

**Comment by anthrotype** [comment]
sorry, I meant Glyphs.app "also shifts their outline to the _left_", not to the _right_.

in other words, it _subtracts_ the advance width from the glyph's horizontal (x) coordinates, including the components and anchors.

**Comment by schriftgestalt** [comment]
Yes. Glyphs is doing that. But you need to shift all components of those marks. Nowadays you can much more on mark positioning. The reason to do the shift was that it would leave the mark in a somewhat OK position if there is not mark positioning.

**Comment by m4rc1e** [comment]
I'm tempted to fix this so I can get cleaner diffs when I'm comparing fonts genned with glyphsapp against fontmake. Any objections?

**Comment by anthrotype** [comment]
see https://github.com/googlefonts/glyphsLib/pull/551#issuecomment-532183247

**Comment by m4rc1e** [comment]
> I personally would prefer if designers explicitly drew their combining mark glyphs with a zero advance width to begin with, instead of relying on the compiler to modify that at export time.

That's a good enough reason not to implement this imo. Instead, I'll write a check in our glyphapp scripts to ensure that comb marks are zero width.

**Comment by anthrotype** [comment]
I remember there was some reason why designer make their combining mark with non-zero width but then Glyphs exports them with 0 width.. something to do with the way they show up in the UI.

**Comment by m4rc1e** [comment]
Ah, I guess it's because of the preview window. The window doesn't insert any whitespace between glyphs so for 0 width glyphs they'd all be overlapping.

**Comment by schriftgestalt** [comment]
When you select several marks in font view and open them in edit view, they would be all on top of each other. Same when you just have some letters and a mark in the middle it would be overlapping with the letters. It is much easier when they all have their own space. The requirement that those marks shouldn’t have a width is purely technical and I try to not bother the users with those.

**Comment by madig** [comment]
Hm. Would it make sense to draw things that are detected as marks differently, i.e. make them not overlap while leaving the technical requirement of zero advance width out of sight?

**Comment by schriftgestalt** [comment]
Any suggestion what that "differently" should be? Those marks come in all kinds of shapes and sizes. Just add the width of the space is not enough. You don’t need to do the left shifting (and I might remove that on some point) but just setting them to zero is by far the easies solution.

**Comment by madig** [comment]
Something like, x-position of rightmost point plus 10% of it? I.e. scale with mark glyph width.

**Comment by schriftgestalt** [comment]
But then you move that rightmost point and your glyphs starts to move.

**Comment by m4rc1e** [comment]
It would be pretty cool to solve this in Glyphsapp's preview window. There could be an option to insert tabs between the characters.

**Comment by khaledhosny** [comment]
Glyphs 3 behavior now matches glyphsLib, and that is also what layout engine do when mark glyphs have non-zero advance width.
