### ISSUE TITLE
apply_instance_data_to_ufo: Resets width class to default even when custom parameter is not set and openTypeOS2WidthClass is set in the UFO

### ISSUE THREAD

**Issue by madig** [googlefonts/glyphsLib#555]
The code at https://github.com/googlefonts/glyphsLib/blob/af5ab0b380ba9fc2100a0b91223d41a9c6bb0400/Lib/glyphsLib/builder/instances.py#L392-L393 simply overwrites whatever is in OS/2's width and weight classes. If there is no weight or width axis to take values from, it takes the default value.

One project has a Designspace for a condensed type face with a `wght` but no `wdth` axis. This causes `apply_instance_data_to_ufo` to overwrite the width class `3` from the default font with `5`. So I suppose we need a way to tell glyphsLib to only change this value if the custom parameter is present or `if instance.info.openTypeOS2WidthClass is None`?

**Comment by anthrotype** [comment]
how about we do it only when there is actually wght and/or wdth axes?
