### ISSUE TITLE
No module named fs

### ISSUE THREAD

**Issue by guidoferreyra** [googlefonts/glyphsLib#559]
I think this probaby is a silly question but I installed glyphsLib (via pip) and when I try to use `glyphs2ufo` on the terminal or `import glyphsLib` in a python script I get `ModuleNotFoundError: No module named 'fs'`

Any ideas? I’m usign Python 3.7.4

Thanks in advance

**Comment by anthrotype** [comment]
Strange. When you pip install glyphsLib it should automatically also install Fonttools with the "ufo" extra requirement which in turn pulls in fs module automatically. Maybe you had already installed Fonttools without the [ufo] extra in your environment and then installed glyphsLib on top of it. You can fix it by doing

pip install -U fonttools[ufo,lxml]

lxml is optional but recommended as it speeds up writing UFOs

**Comment by guidoferreyra** [comment]
Thank Cosimo! It was exactly that.
