### ISSUE TITLE
error exporting UFO when a  GSGlyph contain multiple layers with the same name

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/glyphsLib#566]
when building master UFOs, if a Glyphs's glyph object has more than one supplementary layers with identical name, the builder will attempt to call `ufoLib2.Layer.newGlyph` method twice for the same layer and glyph name, resulting in errors like this

```
[...]
  File "glyphsLib/builder/builders.py", line 222, in masters
    ufo_glyph = ufo_layer.newGlyph(glyph.name)
  File "ufoLib2/objects/layer.py", line 120, in newGlyph
    raise KeyError("glyph %r already exists" % name)
KeyError: "glyph '_part.spirale' already exists"
```

**Comment by anthrotype** [comment]
i am not sure how we should fix this. If it is a common thing to have multiple layers within the same glyph with the same name, then we should support it somehow without losing data. Otherwise, I'd be inclined to simply warn and only save the last duplicate glyph layer.

By the way, when were were using defcon instead of ufoLib2, we were silently taking the last duplicate-name glyph layer.

There is in fact a difference between defcon's and ufoLib2's `newGlyph` methods: the former overwrites any existing glyph, whereas the latter raises an error...

**Comment by schriftgestalt** [comment]
I wouldn’t say it is common but it is possible. e.g. with interpolating 'iColor XX' or 'Color XX' layers. And a 'Color XX' layer might show up twice inside a master. 
So possible setups:
```
Regular 
    Color 1
    Color 2
Bold
    Color 1
    Color 2
```
or 
```
Regular 
    Color 1
    Color 2
    Color 1
```

**Comment by madig** [comment]
I'm inclined to warn and take the last layer.

**Comment by anthrotype** [comment]
> interpolating 'iColor XX' or 'Color XX' layers. And a 'Color XX' layer might show up twice inside a master

is this some special type of layer naming scheme that we should be aware of?

**Comment by anthrotype** [comment]
replying to myself, yes `iColor`layers is for sbix color fonts and are documented here:
https://glyphsapp.com/tutorials/creating-an-apple-color-font

whereas `Color XX` is for COLR/CPAL or OT-SVG color fonts:
https://glyphsapp.com/tutorials/creating-a-microsoft-color-font
https://glyphsapp.com/tutorials/creating-an-svg-color-font

Especially considering that want to support building color fonts (https://github.com/googlefonts/fontmake/issues/30), we _do_ want to make sure we export such layers correctly.

Given that UFO layers must have unique names, glyphsLib should make them unique using some suffix when exporting and strip the suffix upon importing.

**Comment by anthrotype** [comment]
the problem here is that the uniqueness of layers in UFO it is their name, and [layercontents.plist](http://unifiedfontobject.org/versions/ufo3/layercontents.plist/) says layer names must be unique, whereas in Glyphs.app it is given by their ID (which is like a uuid). This allows it to have layers with the same name (but different uuid).
Any suffix scheme will be prone to ambiguities when going back and forth between Glyphs <-> UFO, because layer names may contain any characters.

**Comment by belluzj** [comment]
(same error on Noto Sans Georgian from https://github.com/googlefonts/noto-source/blob/809ac0b/src/NotoSansGeorgian-MM.glyphs)

**Comment by anthrotype** [comment]
@moyogo was working on a PR
https://github.com/googlefonts/glyphsLib/pull/570

**Comment by anthrotype** [comment]
Fixed with #570

**Comment by belluzj** [comment]
Thanks @moyogo and @cosimo! (happy new year!)

**Comment by anthrotype** [comment]
> 'Color XX' layer might show up twice inside a master

but why? If the two supplementary layers (both linked to the same master) bear the same "Color XX", couldn't (should) they be flattened into one? What is the purpose of having two with the same name (color)?

**Comment by anthrotype** [comment]
oh.. the order is important. Now I understood your example above.

```
Regular 
    Color 1
    Color 2
    Color 1
```

Hm not sure what to do. Could Glyphs.app be chaged so that it ignores any extra characters that appear after the "Color XX" string (where XX are digits)?

**Comment by anthrotype** [comment]
> At least the suffix should be removed when the name starts with "Color" or "iColor".

I guess we can do that.

**Comment by anthrotype** [comment]
i'll open a separate issue for this
