### ISSUE TITLE
Set TYPOGRAPHIC_SUBFAMILY_NAME to VF’s origin master's name

### ISSUE THREAD

**Issue by yanone** [googlefonts/glyphsLib#569]
I was told to report an issue here that I don't *fully* understand.

A font [Petrona-ROMAN-MASTER-NEW-W.glyphs.zip](https://github.com/googlefonts/glyphsLib/files/3956251/Petrona-ROMAN-MASTER-NEW-W.glyphs.zip) (attached here) is reported in `fontbakery` with the following failure:
```
 >> com.google.fonts/check/name/typographicsubfamilyname
    Check name table: TYPOGRAPHIC_SUBFAMILY_NAME entries.
    with ./Fonts/vf/Petrona[wght].ttf

    * FAIL: TYPOGRAPHIC_SUBFAMILY_NAME for Win is missing. It must be "Medium". [code: missing-typo-win]

    Result: FAIL
```

The origin master is on the Medium instance, so it appears that Google Fonts likes to have the font's  TYPOGRAPHIC_SUBFAMILY_NAME for Win to be set to this instance's name, *Medium*, in order for legacy apps to render the Medium when Medium is expected.

I was also told to set the font's `Variable Font Origin` custom parameter, to no avail. But as I understand, since the origin can be inferred from the masters/instances setup, this custom parameter is unnecessary.

Did I report that correctly? :)

**Comment by m4rc1e** [comment]
The masters in your file are named incorrectly. The masters and instances must be named so they're related to one another. The relationship is defined by the Axes coordinates. Your Regular master has the same wght axis coordinate as your Medium instance so rename the Regular master to Medium.

**Comment by m4rc1e** [comment]
Your ExtraLight master's wght axis coordinate also matches the Thin instance so rename the ExtraLight master to Thin.

**Comment by yanone** [comment]
I was just gonna say: Now the subfamily name is ExtraLight ;)
Thanks Marc. This solved it. Closing this.
