### ISSUE TITLE
UFO->Glyphs should strip #<digit> suffix from 'Color' layer names 

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/glyphsLib#573]
in #570, we fixed the error when exporting glyphs->UFO and glyphs contain duplicate layers with the same name by appending a `#<digit>` suffix to make the layer name unique (UFO layers must have unique names).

However, @schriftgestalt noted that in Glyphs.app there are some special glyph layers that are used for color fonts ("Color XX" where X are numbers indicating the index of a color palette) and which can occur multiple times with the same layer name string within the same glyph master:
https://github.com/googlefonts/glyphsLib/issues/566#issuecomment-561643874

When going back from UFO -> glyphs, we should check if the layer name starts with "Color XX" and strip any such suffixes.

**Comment by khaledhosny** [comment]
This is already taken care of when handling color layers.
