### ISSUE TITLE
Support "Axes" custom parameter 

### ISSUE THREAD

**Issue by madig** [googlefonts/glyphsLib#585]
Not sure what exactly it does, but I suppose ufo2glyphs can dump the axes from the Designspace into the parameter. What to do for glyphs2ufo? Ignore?

**Comment by schriftgestalt** [comment]
The `Axes` stores the main axes definition:
```
(
	{
		Name = Weight;
		Tag = wght;
	},
	{
		Hidden = 1;
		Name = "Some Name";
		Tag = SMNA;
	}
);
```

**Comment by anthrotype** [comment]
but we _do_ support this one already, don't we?

**Comment by madig** [comment]
@schriftgestalt thanks.

@anthrotype yes but we don't put it into the Glyphs file on ufo2glyphs.

**Comment by madig** [comment]
@schriftgestalt How does `GSFontMaster.axes` work? How does it know how many axes there actually are?

**Comment by schriftgestalt** [comment]
You mean the property in the python wrapper?

https://github.com/schriftgestalt/GlyphsSDK/blob/95ba997589ffc62cb3fbcefbe990661d5e133071/ObjectWrapper/GlyphsApp/__init__.py#L1633

**Comment by madig** [comment]
Oh, interesting. So, how does `countOfAxes()` determine the number of axes? And there's a hard limit of 6 axes?

**Comment by schriftgestalt** [comment]
```
- (NSUInteger)countOfAxes {
	return [[self axes] count];
}
```
and `[self axes]` is accessing the custom parameter.

I added an error when one tries to add more then six axes.

**Comment by madig** [comment]
But how does `axes` know how many axes there are? :grin: Does it check the 6 different master values on every master to see if any of them diverge from the default value?

**Comment by schriftgestalt** [comment]
Axes checks there is a custom parameter. If not, it checks if any master has a none default setting for any of the `widthValue`, `weightValue`,  `customValue`, …

**Comment by madig** [comment]
What does it do when all masters have just `customValue3` set to something non-default?

**Comment by khaledhosny** [comment]
Done a while ago alongside Glyphs3 support.
