### ISSUE TITLE
Component Info does not always reference an anchor; then glyphsLib fails with KeyError

### ISSUE THREAD

**Issue by belluzj** [googlefonts/glyphsLib#589]
Faulty line:
https://github.com/googlefonts/glyphsLib/blob/09e4cb6c07005fc46ebcfc88063ee0a90d6d504c/Lib/glyphsLib/builder/components.py#L67

Example .glif file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="uni00AF" format="2">
	<unicode hex="00AF"/>
	<advance width="573"/>
	<outline>
		<component base="uni0304" xOffset="286"/>
	</outline>
	<lib>
		<dict>
			<key>com.schriftgestaltung.Glyphs.ComponentInfo</key>
			<array>
				<dict>
					<key>alignment</key>
					<integer>-1</integer>
					<key>index</key>
					<integer>0</integer>
					<key>name</key>
					<string>uni0304</string>
				</dict>
			</array>
		</dict>
	</lib>
</glyph>
```

**Comment by anthrotype** [comment]
although it looks like component["name"] and component["anchor"] go together, see:

https://github.com/googlefonts/glyphsLib/blob/09e4cb6c07005fc46ebcfc88063ee0a90d6d504c/Lib/glyphsLib/builder/components.py#L32-L37

**Comment by madig** [comment]
I remember that `COMPONENT_INFO_KEY` is used for more than anchors now, also alignment: https://github.com/googlefonts/glyphsLib/issues/532

**Comment by madig** [comment]
@schriftgestalt is the key used for more than `anchor` and `alignment`? Do you export `locked`?

**Comment by schriftgestalt** [comment]
`locked` is not part of `COMPONENT_INFO_KEY`. But it is a good idea ;)

**Comment by madig** [comment]
Do you export smart component info?

**Comment by schriftgestalt** [comment]
Now I do.
```
<dict>
	<key>index</key>
	<integer>0</integer>
	<key>name</key>
	<string>_part.boxFeet</string>
	<key>pieceSettings</key>
	<dict>
		<key>Feet</key>
		<integer>60</integer>
		<key>Height</key>
		<real>0.335</real>
		<key>Width</key>
		<real>18.233</real>
	</dict>
</dict>
```
And:
```
<dict>
	<key>index</key>
	<integer>0</integer>
	<key>locked</key>
	<true/>
	<key>name</key>
	<string>A</string>
</dict>
```

**Comment by schriftgestalt** [comment]
I have to retract the `pieceSettings` as the layers of the smart component are not exported, yet.
