### ISSUE TITLE
Feature names are not handled

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/glyphsLib#602]
Glyphs seems to (ab)use feature notes for setting features names (see _Names for Stylistic Sets_ section in https://glyphsapp.com/tutorials/stylistic-sets).

Currently glyphsLib will export any thing in the feature notes as a comment.

Test font: [Qahiri.zip](https://github.com/googlefonts/glyphsLib/files/4346480/Qahiri.zip) (`ss01` and `ss02` features).

**Comment by jenskutilek** [comment]
I was surprised to see that in your test font the `featureNames {};` is part of the feature note. I thought only the `Name: XXX` syntax was supported in the note, and if you used the long FDK syntax, it should go into the normal text contents of the feature? Then glyphsLib should export it without further changes. I have no idea how common this is. Should I add support for the full syntax in the node to my PR (#615)?

**Comment by jenskutilek** [comment]
It looks like the featureNames in the note is even preferred by Glyphs (it will display the feature name in the sidebar). I've updated #615.

**Comment by anthrotype** [comment]
> featureNames {}; is part of the feature note

wow, that's quite a hack.

**Comment by jenskutilek** [comment]
It may have an advantage if the feature code is autogenerated, and you still want to add a name without maintaining the rest of the feature manually. But it is quite a hack :)

**Comment by schriftgestalt** [comment]
As Jens said. The `featureNames {}` can be put in the note to allow the code to be autogenerated. 

There are two different possible syntaxes. The `Name:` (only if the first line starts with "Name:", the rest of the line will be used; will only write Windows/English entry). 
Or the full `featureNames {}` block if you need different languages.
