### ISSUE TITLE
Escaped characters in features names are incorrectly unescaped

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/glyphsLib#603]
Related to #602, the font attached there contains Arabic name strings in the feature names block. AFDKO’s makeotf requires non-ASCII characters to be escaped, but glyphsLib will unescape `\062d\0631\0648\0641` into `2d314841`, breaking the string completely.

**Comment by jenskutilek** [comment]
Here's some code to add AFDKO replacement sequences for characters outside ASCII:

https://gist.github.com/jenskutilek/c9adaf1630665c43a7b5e5cc3c7f8b1e

But when you specify the name entry in Glyphs as Unicode (platform 3, encoding 1), I think it's not actually required to escape any characters except " and \ (which this code doesn't handle, and which have to be escaped always in AFDKO strings).

**Comment by anthrotype** [comment]
I think Khaled fixed the lack of UTF-8 support in latest version of makeotf so escape sequences should no longer be required https://github.com/adobe-type-tools/afdko/pull/1133

**Comment by khaledhosny** [comment]
I don’t know if Glyphs uses the new AFDKO yet, so if one is building with Glyphs escaping might still be required.

**Comment by khaledhosny** [comment]
> I don’t know if Glyphs uses the new AFDKO yet, so if one is building with Glyphs escaping might still be required.

The issue about `.glyphs` files with escaped name strings, and I checked latest Glyph release and it still chokes on unescaped ASCII strings, so escaping is still needed if one will be building inside Glyphs.

**Comment by jenskutilek** [comment]
In any case, with #615 escaped characters in name strings are handled correctly as far as I can see.

**Comment by khaledhosny** [comment]
> In any case, with #615 escaped characters in name strings are handled correctly as far as I can see.

It does not fix the issue, unfortunately. If you try with [Qahiri.zip](https://github.com/googlefonts/glyphsLib/files/4346480/Qahiri.zip) and convert it to UFO (with `glyphs2ufo`), the generated feature code for `ss01` and `ss02` looks like: 

```fea
feature ss01 {
# notes:
# featureNames {
#    name "Dot-less Letter Forms";
#    name 3 1 0x0C01 "2d314841 4547454429 (284427 46422737)"; # حروف مهملة (بلا نقاط)
# };
featureNames {
   name "Dot-less Letter Forms";
   name 3 1 0x0C01 "2d314841 4547454429 (284427 46422737)"; # حروف مهملة (بلا نقاط)
};
  sub [@Dots hamzaabove-ar hamzabelow-ar hamza-ar] by empty;
} ss01;

feature ss02 {
# notes:
# featureNames {
#    name "Rounded Dots";
#    name 3 1 0x0C01 "46422737 45332a2f4a3129"; # نقاط مستديرة
# };
featureNames {
   name "Rounded Dots";
   name 3 1 0x0C01 "46422737 45332a2f4a3129"; # نقاط مستديرة
};
  sub @Dots by @Dots.alt1; 
} ss02;
```

IIRC, the issue happens early on while parsing the .glyphs data before creating any objects.

**Comment by anthrotype** [comment]
> the issue happens early on while parsing the .glyphs data before creating any objects.

The culprit is here somewhere:

https://github.com/googlefonts/glyphsLib/blob/1ad88c1dedb3072f1d9e62dc58b268496a1c6bc3/Lib/glyphsLib/parser.py#L210-L230

I believe the problem is the fact that, when parsing a quoted plist string, first we are unescaping all literal backslashes (i.e. `.replace("\\\\", "\\")`, and _then_ we take what's left and perform the octal sequence un-escaping, which leads to `"\\062d"` -> `"\062d"` -> `"\x06" + "2d"`.

The octal sequence parsing should be done before replacing all double-backslashes (a literal backslash) with single backslash, and the `_unescape_re` pattern should not match if preceded by another backslash. After having substituted all octal/unicode sequences, it can do a final pass to `.replace("\\\\", "\\")`, not before.

**Comment by khaledhosny** [comment]
This has been fixed, I assume with the switch to openstep-plist parser.
