### ISSUE TITLE
Infinite loop in GSPath.segments

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/glyphsLib#621]
Glyphs paths *should not* start with a `curve` node, but *sigh* sometimes they do.

![foo](https://user-images.githubusercontent.com/106728/93861114-e89c6600-fcb7-11ea-9e3c-fac750ad45d2.png)

When this happens, `nodeCount` is never advanced in `GSPath.segments` and the loop is never terminated.

**Comment by schriftgestalt** [comment]
This is not mandated. So this is fully supported in Glyphs.
