### ISSUE TITLE
Trigger update to interface when manipulating the glyphs file

### ISSUE THREAD

**Issue by kontur** [googlefonts/glyphsLib#631]
Hey,

I am not sure exactly where or how GlyphsApp determines to update the rendered glyphOrder, but I notice that when I change the glyphOrder programmatically and open the font the glyphOrder is correct, but the rendered interface is in "old" sorting. In the app, subsequently  clicking Glyph > Update Glyph Info will trigger an update to the interface and apply the correctly saved glyphOrder.

```
from glyphsLib.classes import GSFont
font = GSFont("path/to/font.glyphs")
font["glyphOrder"] = ["Z", "A"]
font.save()
```

Then opening the .glyphs file the font interface will still be rendered in "old" sorting. But once using the Update Glyph Info it sorts Z, A, ...

Is there a way to trigger GlyphsApp doing this "update" or simply disregarding the old state by way of how or what is written to the source?

**Comment by madig** [comment]
Sounds like a question for the GlyphsApp forum?

**Comment by schriftgestalt** [comment]
Opening a font doesn’t trigger a resorting (to give you a chance to see the old sorting). Select any glyph and run "Glyph" > "Update Glyph Info" to trigger a sorting.

**Comment by kontur** [comment]
@schriftgestalt If the app retains the "old" glyphOrder before a resort is triggered, how does the app know what is the old order? Do I have to write the glyphs themselves in the desired order to the file for them to appear in the desired glyphOrder when opening the file?

**Comment by schriftgestalt** [comment]
Glyphs reads the glyphs from the file and keeps the order. 
The `glyphOrder` should not be confused with the `public.glyphOrder`. The former is just a hint for the sorting and doesn't need to contain all the glyphs in the font but also can contain extra names.
