### ISSUE TITLE
When fsType set to '0' (editable), glyphsLib sets it to 0x0001

### ISSUE THREAD

**Issue by aaronbell** [googlefonts/glyphsLib#637]
It appears that Glyphs 3 has instituted a change with regards to how fsType is represented in the Glyphs file:

In G2, setting fsType to "Installable" resulted in:
```
{
name = fsType;
value = (
);
}
```

However, now, Glyphs now sets it as:
```
{
name = fsType;
value = (
0
);
}
```

As a result, running the Glyphs file through glyphsLib produces a fsType of 0x0001 rather than 0x0000. Here is a demo font that shows the issue:
[fsType_Demo.zip](https://github.com/googlefonts/glyphsLib/files/5556305/fsType_Demo.zip)

Interestingly, it appears that Glyphs is also mis-exporting this customParameter as well. :/

**Comment by madig** [comment]
Has that file been exported from G3 using the G2 format? glyphsLib has only been tested with what G2 put out and I know of no plans to support G3 in the near future, so...

**Comment by schriftgestalt** [comment]
That change was not intentional. I have fixed it already.

**Comment by aaronbell** [comment]
My question is that if the value is set to “0”, why would glyphsLib set the output to 0x0001? It seems to me like the actual value in the file is not being read.

**Comment by schriftgestalt** [comment]
The fsType parameter stores a list of ints that say what bits are set. Value '0' means bit zero is set and not that the fsType is zero. But bit zero should never be set.

**Comment by aaronbell** [comment]
Thanks Georg. I’ll close this then.
