### ISSUE TITLE
Support Glyphs version 3 file format

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/glyphsLib#643]
Originally posted at https://github.com/googlefonts/fontmake/issues/710

**Comment by schriftgestalt** [comment]
I will have some people doing python stuff. So we can help a bit with this.

**Comment by schriftgestalt** [comment]
And this time I made a validator for the file format. That should help with the implementation: https://github.com/schriftgestalt/GlyphsSDK/tree/Glyphs3/GlyphsFileFormat/validator

**Comment by simoncozens** [comment]
I am working on this. I would like some discussion (cc @anthrotype), however, about what kind of approach is best:

1. Read both G2 and G3 files into a common set of (current, Glyphs 2-based) classes. Sort out conversion from/to Glyphs 3 during load and save.
2. Read both G2 and G3 files into a common set of Glyphs 3-based classes. Sort out conversion from/to Glyphs 2 during load and save.
3. Read G2 files into G2-based classes and G3 files into G3-based classes.

(When I mean "Glyphs 3-based classes", I mean things like the `GSAxes` structure, the glyphs3 namings of things (`GSComponent.ref` instead of `GSComponent.name` etc.)

1 is probably the least intrusive to the current codebase, but the most ugly.
2 is probably the most forward-compatible, but the biggest change.
3 is probably the easiest, but the least maintainable.

So, which way should we go?

**Comment by anthrotype** [comment]
Thanks Simon for working on this. In an ideal world, number 2. would be preferable. But I don't know the extent of the changes.
Also -- perhaps unrelated -- this may be an opportunity to make use of the much faster https://github.com/fonttools/openstep-plist. There were some quirknesses in glyphs2 format that prevented us from using that (e.g. unquoted unicode hex strings that could be confused with decimal integers), but I believe Georg has addressed them in glyphs3.

**Comment by simoncozens** [comment]
Relevant: https://github.com/schriftgestalt/GlyphsSDK/pull/40/commits/cc16de6c3dcdbfa002fd89efd77aa3944408d6b3

**Comment by stone-zeng** [comment]
Can you consider to implement the support of `.glyphspackage` format? It will be espeically helpful for huge char sets, e.g. CJK fonts.

At present (with pr #652) I can still only parse the package into `OrderedDict` and write it to a `.glyphs` file then read again.

**Comment by anthrotype** [comment]
Can you provide more info as to how this glyphspackage work?
Googling around doesn't yield much, I just found https://forum.glyphsapp.com/t/are-glyphspackage-stable/16744 -- which is kinda vague.

**Comment by schriftgestalt** [comment]
I'll ad details to the specs page. 

It is a package with the content of each glyph element in a .glyph file in a glyphs folder. All the rest is in a single .plist file.

**Comment by anthrotype** [comment]
sounds good, thanks Georg!

**Comment by stone-zeng** [comment]
Note that the order of the glyphs (`*.glyph`) are stored in a separate `order.plist` files, and the `displayStrings` etc are stored in `UIState.plist` for convenience of git users.

**Comment by schriftgestalt** [comment]
I added a version brief section about .glyphspackage files in the GlyphsFileFormatv3.md file and added a sample file.

**Comment by weiweihuanghuang** [comment]
What's the progress here?

**Comment by simoncozens** [comment]
Oh, I did it. It works fine. Pull request [here](https://github.com/googlefonts/glyphsLib/pull/652). Just put `git+git://github.com/simoncozens/glyphsLib@glyphs3-try3#egg=glyphsLib` into your requirements.txt (or run `pip3 -U git+git://github.com/simoncozens/glyphsLib@glyphs3-try3#egg=glyphsLib`) and get on with your day.

**Comment by simoncozens** [comment]
(Note that's just the base Glyphs 3 file format, not .glyphspackage. I'm not *that* fast.)

**Comment by weiweihuanghuang** [comment]
Oh I see, I'm particularly curious about support for the new 'alternate layer' and 'intermediate layer' (fka bracket and brace tricks) formatting.

**Comment by simoncozens** [comment]
Oh, hrm. I am not sure if that is working. It might be. Variable layout is a challenging problem.

**Comment by weiweihuanghuang** [comment]
It's pretty important I'd say, since you're almsot always going to use alternate layers and intermediate layers if you have a range of weights or widths or any other axes.

**Comment by stone-zeng** [comment]
In Glyphs 3 the `weightClass` value now becomes an int rather than a string, so

```diff
diff --git a/venv/lib/python3.9/site-packages/glyphsLib/builder/axes.py b/venv/lib/python3.9/site-packages/glyphsLib/builder/axes.py
index 76a9c2b5..f268db09 100644
--- a/venv/lib/python3.9/site-packages/glyphsLib/builder/axes.py
+++ b/venv/lib/python3.9/site-packages/glyphsLib/builder/axes.py
@@ -77,7 +77,10 @@ def user_loc_string_to_value(axis_tag, user_loc):
         try:
             value = _nospace_lookup(WEIGHT_CODES, user_loc)
         except KeyError:
-            return None
+            try:
+                value = int(user_loc)
+            except ValueError:
+                return None
         return class_to_value("wght", value)
     elif axis_tag == "wdth":
         try:
```

**Comment by weiweihuanghuang** [comment]
Hey how’s it going :)

**Comment by simoncozens** [comment]
Still waiting for maintainers to review and merge this PR, but it's a big and invasive change, so nobody really has the headspace to take it on. :-(

**Comment by m4rc1e** [comment]
I'm tempted to look into this next week.

My plan is to convert every glyphs file I have to v3 (around 80) and then do some black box testing to begin with. I think this approach could get us very far. After black boxing we can check the code itself.

**Comment by m4rc1e** [comment]
@vv-monsalve @RosaWagner we should probably look into this for one of our Thursday sessions.

**Comment by weiweihuanghuang** [comment]
That would be wonderful. I’ve just found that my statics generated in G3 vs the VFs different a bit too much than what I’d comfortably deliver to a cliebt

**Comment by simoncozens** [comment]
Note that in a recent commit (5102f8a) I fixed a weight/width class error (mentioned by @stone-zeng above), which may help with your differences - so if you haven't already done so, use git pull to update to the latest commit on that branch.

**Comment by davelab6** [comment]
> In an ideal world, number 2. would be preferable. 

@simoncozens Just to confirm, that was the approach taken in the PR #691 ?

**Comment by simoncozens** [comment]
Correct, yes. I *did* warn it was going to be a big change...

**Comment by weiweihuanghuang** [comment]
Was support added?

**Comment by khaledhosny** [comment]
> Was support added?

Yes, to the beta release but we should have a stable release soon.

**Comment by stone-zeng** [comment]
It seems that `.glyphspackage` is still not supported?

**Comment by jvgaultney** [comment]
Any progress on this? Is there a plan to fully support v3 format or should we prepare to stick with v2 for the forseeable future?

**Comment by anthrotype** [comment]
@jvgaultney glyphs v3 is marked as "supported" as of glyphsLib v6.0.0 but there may still be bugs of course. I'd suggest to  file specific issues than resurrect this one.

**Comment by jvgaultney** [comment]
Sorry - I had mistakenly posted in this old issue. See this open issue: https://github.com/googlefonts/glyphsLib/issues/754
