### ISSUE TITLE
_ensureMasterLayers doesn't

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/glyphsLib#646]
classes.py has this code:

https://github.com/googlefonts/glyphsLib/blob/6c409dd27cb46919c7fe10c5db2b77ce45751632/Lib/glyphsLib/classes.py#L855-L858

I believe the commented code is correct and the uncommented test is wrong.

With current code:

```
>>> import glyphsLib
>>> g = glyphsLib.GSFont("tests/data/MontserratStrippedDown.glyphs")
>>> newGlyph = glyphsLib.GSGlyph()
>>> newGlyph.name = "foobar"
>>> newGlyph.parent = g
>>> g.glyphs.append(newGlyph)
>>> g.glyphs["foobar"].layers._ensureMasterLayers()
>>> print(g.glyphs["foobar"].layers)
()
```

Swapping current code for commented code:

```
>>> import glyphsLib
>>> g = glyphsLib.GSFont("tests/data/MontserratStrippedDown.glyphs")
>>> newGlyph = glyphsLib.GSGlyph()
>>> newGlyph.name = "foobar"
>>> newGlyph.parent = g
>>> g.glyphs.append(newGlyph)
>>> g.glyphs["foobar"].layers._ensureMasterLayers()
>>> print(g.glyphs["foobar"].layers)
(<GSLayer "Light" (foobar)>, <GSLayer "SemiBold" (foobar)>, <GSLayer "Bold" (foobar)>)
```

**Comment by simoncozens** [comment]
However! With my correction, this test fails:

```
    def test_layers_missing_master(self):
        """
        font.glyph['a'] has its layers in a different order
        than the font.masters and an extra layer.
        Adding a master but not adding it as a layer to the glyph should not
        affect glyph.layers unexpectedly.
        """
```

Note that the comment and the call to `_ensureMasterLayers` contradict each other.

**Comment by anthrotype** [comment]
according to git blame Jany wrote that code, so I defer to him

**Comment by anthrotype** [comment]
/cc @yanone who added that `_ensureMasterLayers` in the first place
https://github.com/googlefonts/glyphsLib/commit/5aa5ee7acbe4c3764c2dd551f4b518f6cd345042

**Comment by belluzj** [comment]
My contribution here was to add the two commented lines... I can't remember what I saw then but was probably thinking the same as @simoncozens but didn't go all the way to replace the existing test with my version.

![image](https://user-images.githubusercontent.com/3616772/100906058-a7e37900-34c0-11eb-8a48-9447e9e67fd6.png)

From https://github.com/googlefonts/glyphsLib/commit/aa326c2b757bd98eeff98c5af4dde044cedba26e#diff-e6b2643e223b682bd452c80e92b60906ac9d497f1ddb131cab0b14096fd0bc26R729-R730 (you have to expand the diff on classes.py)

**Comment by belluzj** [comment]
The test is from @moyogo https://github.com/googlefonts/glyphsLib/commit/ff0310767848edb9f71c33caefa131fda1e61fd7

**Comment by simoncozens** [comment]
I think since this does produce different behaviour to Glyphs, the current code *and* the @moyogo test are wrong. (But that's only because I'm trying to run Glyphs scripts on the command line...)

**Comment by behdad** [comment]
> can anybody (e.g. @yanone who added it in the first place) explain what is (or was) the purpose of this `_ensureMasterLayer`? According to https://programsareproofs.com/articles/functiontrace_glyphslib.html, this method is called too frequently and outright removing it considerably reduces the runtime.

Indeed. My profiling suggests that as well. We should optimize it somehow.

**Comment by khaledhosny** [comment]
I’m having hard-time getting this code to do anything and I removed it completely and not a single test failed.

Reading the code I fail to see how it can do anything:
https://github.com/googlefonts/glyphsLib/blob/4e461419040b57b7bb968b067f71a1c1ed0975ad/Lib/glyphsLib/classes.py#L934-L942

It is iterating over all masters in the font, then tries to access the master by its id and then checks if the master is None, but this can never happen since we are iterating over already existing masters.

If this code is not doing anything, there is no point in having it (it takes over 50% of the time of building my font).

There is no point also arguing what the correct version should, if the issue it is trying to fix is real somebody would have complained by now.

**Comment by schriftgestalt** [comment]
Im working on the Glyphs 3 compatibility right now (check the Glyphs3 branch for the current state). The next item id to improve performance. In an initial test I tried to remove this function and found that it wasn't changing anything. 

I think the purpose was to add layers to a glyph that was added in code. But one could write the script to add the layers.
