### ISSUE TITLE
Add FeatureParamsStylisticSet in FeatureRecord

### ISSUE THREAD

**Issue by kosbarts** [googlefonts/glyphsLib#662]
Currently when exporting from a Glyphs file the custom naming of Features is dropped.
Is it possible to update and include it?

**Comment by anthrotype** [comment]
this is implemented in this PR https://github.com/googlefonts/glyphsLib/pull/615

I actually forgot what the outstanding issues where that prevented the merge and have no time to dig deeper at the moment.

Maybe @jenskutilek or @madig remember?

**Comment by jenskutilek** [comment]
I need to have a look again.

**Comment by khaledhosny** [comment]
Duplicate of #602
