### ISSUE TITLE
Applying Replace Prefix etc. custom parameters to masters?

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/glyphsLib#669]
I’m trying to fix [this issue](https://forum.glyphsapp.com/t/contextual-gpos-adjustements-per-master-in-glyphs-2/18177/2). I managed to fix it for static instances by using `Replace Prefix` custom parameter to change the `valueRecordDef`’s. Unfortunately, Glyphs does not support `Replace Prefix` for masters. Would it make since to use the instance `Replace Prefix` if it has the same location as master, or simpler support `Replace Prefix` for masters even though Glyphs does not support it?

**Comment by khaledhosny** [comment]
Decided not to pursue this any further and Glyphs 3 tokens should be usable for this.

**Comment by khaledhosny** [comment]
Actually `Replace Prefix` in masters seems to be taken into account, apparently glyphsLib does not really care if it is set on master or instance.

**Comment by anthrotype** [comment]
yes, it does work. I've actually suggested this as a ad-hoc solution for projects that needed to have variable positioning rules across masters, even though it does not work from within Glyphs.app.. Not ideal, but at least kind of works. Ideally we should support these new Glyphs 3 tokens (though I haven't looked into how they work yet).

**Comment by khaledhosny** [comment]
Not working from within Glyphs is not an issue for me, I almost never build the fonts with Glyphs, but I need to convince the designers as well... Glyphs 3 token aren't any better currently as they are not variable either.

**Comment by schriftgestalt** [comment]
We are working on variable feature code. Will publish this if we have a woking prototype (I like to know that it actually works).
