### ISSUE TITLE
Designspace file not generating with correct source master location

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/glyphsLib#671]
[test.zip](https://github.com/googlefonts/glyphsLib/files/6191275/test.zip)

I am trying to test Fontmake's behaviour with transformed components. Font has 2 letters and 2 masters.

With Glyphs3 I have this output message:
`fontmake.errors.FontmakeError: In 'Test.glyphs' -> 'master_ufo/Test.designspace': Generating fonts from Designspace failed: Can't find base (neutral) master in DesignSpace document`

And indeed, both masters have location `xvalue=100` in designspace file although in source they have `400` and `700`.
And using Glyphs2 I have the builder` Key Error : axisOrder` (tried to resolve it with axis mapping and axis order key in config.yaml but didn't do the job).

Boh this is curious.

**Comment by moyogo** [comment]
The Glyphs3 format isn't yet supported in main, only the branch from #652 supports it.
With main, glyphsLib seems to fail silently and uses 100 as a default value when writing the designspace.
Maybe glyphsLib should fail properly until #652 is merged in.

The gftools builder error is a gftools builder error: I've opened https://github.com/googlefonts/gftools/pull/351.

**Comment by RosaWagner** [comment]
Thanks Denis for the answer :)
