### ISSUE TITLE
Handle Unicode Variation Sequences

### ISSUE THREAD

**Issue by moyogo** [googlefonts/glyphsLib#681]
Since [GlyphsApp 2.6.1](https://glyphsapp.com/news/glyphs-2-6-1-released) Glyphs files can have some UVS support:
> Preliminary support for Unicode Variation Sequences: add a .uvXXX suffix to the alternate glyph, with XXX ranging from 001 to 256.

While this is incomplete, as it doesn't support default UVS or duplicates glyphs when it doesn't need to (see https://forum.glyphsapp.com/t/unicode-variation-sequences/11813/7), glyphs2ufo should probably do something with that data and fill in or update `public.unicodeVariationSequences` in the font.lib.

**Comment by schriftgestalt** [comment]
Thanks for reminding me about the missing default UV mappings. I just fixed this. This is fully handled on export so glyphsLib can implement this properly already (using the manually set mappings from the .glyphs file and the default mappings from the Unicode data).
