### ISSUE TITLE
ufo2glyphs results in glyphs file with contours on "foreground" layer (as opposed to master layers)

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/glyphsLib#687]
Scenario:

- I have a designspace set up, pointing to two UFOs (Thin & Black)
- I have used `ufo2glyphs` to convert this to a Glyphs file
- When I open the Glyphs file, it appears to be empty. It’s not – all of the glyphs just have contours on the `foreground` layer (treated as the default layer of a UFO by RoboFont), which GlyphsApp treats as separate from the main master layer of a glyph.

Is there an easy way to convert the `foreground` layers to the master layers, for all masters and all glyphs? I can do this in a single glyph by right-clicking the `foreground` and selecting “Use as master.” Obviously, that would be silly to do a full character set, so I’m sure I could also figure out a script to do this for all glyphs in a Glyphs document. But, is there an existing function or tool for this (included in or separate from glyphsLib)? 

Could there be some kind of step that I’m missing that could do this in the CLI – something like `ufo2glyphs familyname-wght.designspace --defaultlayer foreground`?

Thanks for any info!

**Comment by moyogo** [comment]
This should have been addressed in #664.

**Comment by arrowtype** [comment]
Oh, nice! If I install the latest dev version (`pip install -U git+https://github.com/googlefonts/glyphsLib`), the layers seem to work out as expected.

Thank you, @moyogo!

**Comment by arrowtype** [comment]
(Feel free to close this if you want.)

**Comment by moyogo** [comment]
Oh we haven't done a release for a while.
