### ISSUE TITLE
Detect glyphs version 3 and exit gracefully

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/glyphsLib#689]
![Screenshot from 2021-06-16 18-35-38](https://user-images.githubusercontent.com/213676/122297575-107ccb00-ced2-11eb-9c5e-84ae63f89a8f.png)

Seems to be a bug, but I am not sure. It was found at:
https://github.com/benhoepner/National-Park/issues/2

**Comment by felipesanches** [comment]
Since support for Glyphs 3 from @simoncozens branch was not yet merged, I'd suggest detecting the file format version and exit gracefully letting the user know that it is not yet supported (but "coming soon").

**Comment by simoncozens** [comment]
G3 support is now merged.

**Comment by felipesanches** [comment]
thanks
