### ISSUE TITLE
Is there a way to skip non-main layers?

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/glyphsLib#695]
I am attempting to use `glyphs2ufo` to go from a Glyphs file that includes Latin, Arabic, and Cyrillic scripts. Many of the glyphs have duplicate layers. Most commonly, this is `foreground` ... maybe these started as UFOs, though I’m not sure. Some glyphs have a large number of layers with duplicate names (maybe 10–15).

If I use the default `ufoLib2` UFO module, the program gets stuck on a “duplicate” glyph, which actually seems to be from a glyph with duplicate layer names.

```
...
  File "/Users/stephennixon/type-repos/<project>/venv/lib/python3.9/site-packages/ufoLib2/objects/layer.py", line 296, in newGlyph
    raise KeyError(f"glyph named '{name}' already exists")
KeyError: "glyph named 'dblparenright' already exists"
```

I can get around this by using @moyogo’s branch from https://github.com/googlefonts/glyphsLib/pull/570.

However, that results in over 2000 layer directories in the UFOs, making them practically impossible to handle with other tools like RoboFont and fontParts FontShell. This is almost an added layer per glyph, though not quite.

![image](https://user-images.githubusercontent.com/45946693/124818667-4f35fc00-df39-11eb-809c-46d7a26ba858.png)

I’ve found that I can alternatively get around the initial blocker in the main `glyphsLib 5.3.2` release, if I instead use the option `--ufo-module defcon`. Still, though, this results in several hundred layers, which I still don’t want:

![image](https://user-images.githubusercontent.com/45946693/124817944-6d4f2c80-df38-11eb-9dee-776fe901f8ce.png)

Is there a way to perhaps ignore all layers aside from the master layers and bracket layers?

Short of that, I suppose I could either blast those layers away with either a script in GlyphsApp, or perhaps with some quick file and text handling Python for the UFOs. But, if there is a better way, I’d like to use it!

Thanks, as always, for such a helpful tool, and thanks for any insights here.

**Comment by arrowtype** [comment]
Quick update here... [this GlyphsApp script](https://github.com/sergio391/Mekkablue-Glyphs-Scripts/blob/aab8a00522dd90442d89b10fa1f560b215ce9c99/Masters/Delete%20all%20non-Master%20layers.py) worked well to remove the non-master and non-bracket/brace layers. That, in turn, allowed me to generate some clean UFOs. 

This isn’t quite ideal, because it’s not quite as repeatable as an option directly in `glyphs2ufo`. But, if I dig in a bit, I could perhaps write a custom converter with glyphsLib, which could do this layer cleanup step... is this the kind of thing people do with glyphsLib, or am I off-base on that strategy?

**Comment by khaledhosny** [comment]
I think #674 should help with that.

**Comment by arrowtype** [comment]
Awesome, thanks for pointing me to that, @khaledhosny!

**Comment by khaledhosny** [comment]
The minimal option is on main branch now.
