### ISSUE TITLE
EraseOpenCornersFilter crashes on collinear segments, may produce incompatible outlines

### ISSUE THREAD

**Issue by madig** [googlefonts/glyphsLib#703]
https://daltonmaag.github.io/pipeline-perf-tracker/results/ shows failures for Sofia Sans and Noto Sans LCG.

> fontmake: Error: In '../../../downloads/narrow_build_vf_from_glyphs/Sofia_Sans__960_glyphs__7_masters_/SofiaSans/SofiaSans-VF-New.glyphs' -> 'master_ufo/SofiaSans.designspace': Generating fonts from Designspace failed: division by zero

> ERROR:cu2qu.ufo:Glyphs named 'uni1D21' have different number of segments
> Got exit code 0, exiting
> fontmake: Error: In '../../../downloads/narrow_build_vf_from_glyphs/Noto_Sans_LCG__3780_glyphs__8_masters_/NotoSans/NotoSans-MM.glyphs' -> 'master_ufo/NotoSans.designspace': Generating fonts from Designspace failed: fonts contains incompatible glyphs: 'uni1D21'

**Comment by madig** [comment]
The Sofia Sans issue seems to stem from the erase open corners filter:

```
fontmake: Error: In '..\ufo-perf-tracker\bundled_sources\SofiaSans\SofiaSans-VF-New.glyphs' -> '..\..\..\..\..\NIKOLA~1.WAX\AppData\Local\Temp\masters\SofiaSans.designspace': Generating fonts from Designspace failed: division by zero
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Dev\fontmake\Lib\fontmake\font_project.py", line 960, in run_from_designspace
    self._run_from_designspace_interpolatable(
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Dev\fontmake\Lib\fontmake\font_project.py", line 1040, in _run_from_designspace_interpolatable
    self.build_variable_font(
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Dev\fontmake\Lib\fontmake\font_project.py", line 331, in build_variable_font
    font = ufo2ft.compileVariableTTF(
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Dev\glyphsLib\Lib\glyphsLib\filters\eraseOpenCorners.py", line 112, in filter
    contour.draw(p)
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Dev\glyphsLib\Lib\glyphsLib\filters\eraseOpenCorners.py", line 39, in closePath
    self.endPath()
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Dev\glyphsLib\Lib\glyphsLib\filters\eraseOpenCorners.py", line 62, in endPath
    for i in segmentSegmentIntersections(segs[ix - 1], segs[next_ix])
```

**Comment by madig** [comment]
What seems to blow up are lines sitting on the same x-coordinate like here:

![image](https://user-images.githubusercontent.com/380829/129572755-4bbaf8e7-3941-4c04-a943-60fb089b58e8.png)

This middle segment is "points on the same line" in Light and Condensed Light but not in other masters.

The line https://github.com/fonttools/fonttools/blob/f04cb29fc498b5a4430228ebb1bd960d6b52f50e/Lib/fontTools/misc/bezierTools.py#L937 then becomes `(657 - -2) / (420 - 420)`.

Reproducer: `lineLineIntersections((420, -92), (420, -5), (420, -2), (420, 657))`

**Comment by madig** [comment]
@simoncozens is the code doing the right thing?

**Comment by madig** [comment]
The problem with Noto seems to be that open corner erasure produces incompatible outlines.

**Comment by simoncozens** [comment]
Obviously dividing by zero is not the right thing. :-) The question is why the `math.isclose` lines above aren't catching it.

**Comment by madig** [comment]
(Applying filters manually to the Noto sources, the SemiBold `uni1D21` is incompatible with the rest of the sources)

**Comment by madig** [comment]
So, I'm not familiar with the intersection code. Is there any instance where division by zero is an expected outcome? Otherwise I can look into blasting it with Hypothesis to find all the crashers.

**Comment by madig** [comment]
So, `lineLineIntersections` explicitly does not handle segments being collinear, which happens to be what the segments in question here are. I suppose... One could change the function to handle the collinear case with no, one or infinite intersections depending on overlap of the segments? Not sure how to handle the last case though?

**Comment by madig** [comment]
So, two problems:

1. Line intersection math does not deal with collinearity, I can look into making it deal with it somehow (instead of infinite intersections with overlapping segments, return the middle intersection between the end of seg1 and start of seg2.
2. Some glyphs are made incompatible. Not sure what to do there yet.

Maybe I should disable the filter by default for now...

**Comment by anthrotype** [comment]
> Maybe I should disable the filter by default for now...

FWIW I did express my concerns about enabling it by default https://github.com/googlefonts/glyphsLib/pull/663#issuecomment-802020081

If the filter could be fixed soon, we should fix it. If not, we have no choice but disable and make it optional.
In particular, the issue about glyphs being made incompatible is worrying because currently ufo2ft filters are designed to be run one-by-one for each font individually, expect for the cu2qu conversion which is handled specially in the preProcessor.

**Comment by madig** [comment]
@schriftgestalt how does compatible open corner removal work, e.g. for VFs?

**Comment by schriftgestalt** [comment]
You need to have the open corner in all masters.

**Comment by madig** [comment]
Ok, so by definition you cannot have a "folded" open corner in one master and a proper one elsewhere to make some funky interpolation work? They must be constructed such that the same algorithm can work on individual masters while they all implicitly stay compatible?

**Comment by schriftgestalt** [comment]
For variable fonts, only the outside open corners are removed. All inside ones are kept for exactly that reason.

**Comment by madig** [comment]
Yes, so the corners must be made such that the algorithm can clearly detect them across the design space? No folding shenanigans?

**Comment by simoncozens** [comment]
What do you mean by "folded" corner? Are you talking about inside versus outside corners?

**Comment by madig** [comment]
Imagine the left one being completely flat and the right one being your standard open corner in a master somewhere (funky hypothetical corner case). Would the algorithm be expected to cut the open corner in both cases to keep things compatible?

![image](https://user-images.githubusercontent.com/380829/130038285-561f6294-913f-40f6-8a49-ad339aadc3d5.png)

**Comment by belluzj** [comment]
Basically we're wondering about the edge case of a corner becoming all flat in some part of the designspace (all 3 segments overlapping on the same line) because while looking at the code for segment-segment intersection we noticed that the case of two segments that are parallel but on the same line was not handled (or was returning an empty intersection) when actually the intersection would be "all points on the common segment".

In the example below, if you're looking for the intersection between segments AB and CD, the (math) result would be: all points on segment BC. However that's not a convenient answer for the purpose of removing the "flat" version of the open corner in a compatible way. We thought maybe the code could answer that the intersection is this point Z in the middle of the BC segment? That would lead to the removal of the open corner in a way that looks compatible with the other open corner.

![image](https://user-images.githubusercontent.com/3616772/130040308-0f712555-2e57-4f93-95d3-99f6b34a7553.png)


(also maybe we're worrying about a use-case that will never happen in practice, that's a fair answer too)

**Comment by schriftgestalt** [comment]
In Glyphs, the algorithm checks if point A and D are to the right if line B-C (when looking from B to C). In the first example, they are collinear and not on either side. So nothing is removed. Such a setup will not export in Glyphs. And I think that is OK.

**Comment by belluzj** [comment]
Ok, thanks Georg! Yes if Glyphs doesn't deal with the setup then there's no point in trying to support it. Maybe we should check that the code above (that decides on which side the points are) behaves like what Georg suggests?

**Comment by madig** [comment]
Sofia Sans has a weird edge-casey kgreenlandic, where a contour loops back onto itself:

![image](https://user-images.githubusercontent.com/380829/134196472-26a4aadb-5299-4077-92a6-b13511db2d78.png)

**Comment by simoncozens** [comment]
> Maybe we should check that the code above (that decides on which side the points are) behaves like what Georg suggests?

We did that: [explanation from Georg](https://github.com/googlefonts/glyphsLib/pull/663#issuecomment-787056047), [commit](https://github.com/googlefonts/glyphsLib/pull/663/commits/8a29129f8ac1c4757105e8139762b753ac4088a8).

**Comment by simoncozens** [comment]
I'm looking at the incompatible outlines issue now, and have it down to a minimal test case.

**Comment by madig** [comment]
Thanks. Here's my current testing stub FWIW: [a.txt](https://github.com/googlefonts/glyphsLib/files/7209694/a.txt)

**Comment by simoncozens** [comment]
OK, so this open corner is not being processed:

<img width="548" alt="Screenshot 2021-09-22 at 11 18 43" src="https://user-images.githubusercontent.com/106728/134326400-3307cea7-0368-4441-9ff5-8ba3e4e61fd0.png">

```
Considering intersections between ((444, 362), (330, 286)) and ((315, 296), (353, 296), (398, 256), (432, 213))
Point intersections: [Intersection(pt=(338.33261272336455, 291.5550173221714), t1=0.9269069059353987, t2=0.198641)]
Line is: [((330, 286), (315, 296))]
Pt (444, 362) is left of line is: False
Pt (432, 213) is left of line is: True
```

It is not true that both points are "left of line", so this is skipped.

I'm gonna need help here. @schriftgestalt?

**Comment by simoncozens** [comment]
Oh, d'oh, I should using the outgoing handle instead of the end point of the segment.
