### ISSUE TITLE
Exception layer handling is very fragile

### ISSUE THREAD

**Issue by jenskutilek** [googlefonts/glyphsLib#713]
I have a VF Glyphs 3 file with a lot of intermediate layers. I get all kinds of errors when trying to convert them to UFO/designspace with glyphsLib. Sorry, I can't share the font.

glyphsLib seems to deduce the master location solely from the layer name. I was getting errors about duplicate layer names that I absolutely couldn't find inside Glyphs, even by searching through all `GSLayer.name`s.

Apparently in Glyphs 3, the original layer name is never changed when making the layer an"intermediate", it stays at e.g. "Aug 26, 2021, 16:41" or whatever. The displayed name in Glyphs seems to be constructed from `GSLayer.attributes["coordinates"]`, e.g. `{"a01": "500", "a02": "50"}`, which is shown as `{500, 50}`. This is also what `GSLayer.name` returns. The original name from inside the file is never shown.

When I assign a new name to `GSLayer.name` via script, the original hidden name is overwritten, but this isn't noticeable anywhere except by digging in the glyphs file with a text editor.

* glyphsLib should take the axis location of exception layers from `GSLayer.attributes["coordinates"]`.

OK, I can script that, rename all exception layers to match the naming scheme that glyphsLib will understand.

But now I run into another issue, it seems all exception layers for the same location must be associated with the same master, otherwise they will end up in different UFOs, causing duplicate location entries in the sources section of the designspace.

* glyphsLib should unify the axis locations of exception layers from different masters.

Of course I can script that too and just attach all intermediate layers to the first master...

None of this fiddling is required when exporting the variable font directly from Glyphs.

**Comment by madig** [comment]
I think the current code does not yet deal with the new Glyphs.app v3 way of doing coordinates, only the code to handle the file format was updated.

Not sure if we handled same axis locations in different masters before, sparse/brace layer handling in the Designspace world assumes all glyphs for a location come from one source layer. And since we go .glyphs → Designspace → font, we have additional constraints that a Glyphs.app export does not have...
