### ISSUE TITLE
Intermediate/brace layers are not supported anymore

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/glyphsLib#741]
https://github.com/emmamarichal/league-spartan

`fontmake.errors.FontmakeError: In 'LeagueSpartan.glyphs' -> 'master_ufo/LeagueSpartan.designspace': Generating fonts from Designspace failed: '{500}'`

- font is Glyphs version2
- has intermediate layer at 500 for /e and /a.ss01
- ufo2ft creates a source master at 500 in design space, which has the same name as the origin master at 200, which creates a conflict. 

I don't know at which commit exactly the change occurred though. Maybe it's not even glyphsLib the issue.

```
  <sources>
    <source filename="LeagueSpartan-ExtraLight.ufo" name="League Spartan ExtraLight" familyname="League Spartan" stylename="ExtraLight">
      <lib copy="1"/>
      <groups copy="1"/>
      <features copy="1"/>
      <info copy="1"/>
      <location>
        <dimension name="Weight" xvalue="200"/>
      </location>
    </source>
    <source filename="LeagueSpartan-ExtraLight.ufo" name="League Spartan ExtraLight {500}" layer="{500}">
      <location>
        <dimension name="Weight" xvalue="500"/>
      </location>
    </source>
```

[sources.zip](https://github.com/googlefonts/glyphsLib/files/7425902/sources.zip)

**Comment by simoncozens** [comment]
I can't reproduce this. I get the same sources as you do in the designspace file, and the font builds fine with

fonttools==4.27.1
ufo2ft==2.24.0
fontmake==2.4.2

both using fontmake and gftools-builder.

**Comment by RosaWagner** [comment]
I updated gftools again today and I can't reproduce anymore neither. 
@emmamarichal can you try again on your side with upgrading gftools in your venv? maybe it was an issue with some dependency or something.

**Comment by RosaWagner** [comment]
Ah no, doesn't work if I install the main branch of fontmake and glyphsLib.

**Comment by weiweihuanghuang** [comment]
I’m having the same issue https://github.com/weiweihuanghuang/Work-Sans/pull/67#issuecomment-1000334604

**Comment by kosbarts** [comment]
I am having the same issue with fontmake 3.1.2.

**Comment by RosaWagner** [comment]
This issue is blocking the CI builds in multiple repositories, I have complains from several designers.

**Comment by simoncozens** [comment]
Sorry. I shall look at this today.

**Comment by simoncozens** [comment]
Unfortunately I *still* can't reproduce this (at least from the test sources given above). :-/

glyphsLib==master
ufo2ft==2.25.3.dev3+g32fa83c
fontmake==3.1.1.dev3+g24ce22a

Please let me know what versions you are using.

**Comment by simoncozens** [comment]
OK, the problem is in the "minimal" build idea.

**Comment by RosaWagner** [comment]
thanks @simoncozens!
I just tried and I have this error (with Glyphs 3): 

```
DesignSpace sources contain duplicate locations; varLib expects each master to define a unique location. Make sure that you used consistent 'brace layer' names in all the glyph layers that share the same location.
  ['Intermediate {390, 100}', '{390}'] => {'Weight': 390}
```

First I though it was because the intermediate layer was sharing the same location as the Regular instance, so I changed the location, but then I found a conflict between the layer's name and the actual location of the brace layer (cf video).
If I remove the layer name (empty), I have this error:

`Generating fonts from Designspace failed: ''`

If I rename the layer with the same value as the brace layer location, it works. Boh it is annoying but solvable, just wanted to report in case people have the same issue.

https://user-images.githubusercontent.com/12222436/150994540-76a76a51-8f65-4fac-be23-0bf13a992250.mov

**Comment by weiweihuanghuang** [comment]
@RosaWagner @simoncozens this is because in Glyphs 3, the location of a brace layer or alternate glyph is no longer in the layer’s name but a layer property. See https://docu.glyphsapp.com/#GSLayer.attributes

**Comment by weiweihuanghuang** [comment]
What’s the status?

**Comment by RosaWagner** [comment]
the issue described in this comment https://github.com/googlefonts/glyphsLib/issues/741#issuecomment-1021234637 is still happening. @simoncozens shall we re-open that issue?

**Comment by kosbarts** [comment]
Yes please! This is so annoying.

**Comment by weiweihuanghuang** [comment]
Can we make this priority, a lot of projects need intermediate and alternate layers.

**Comment by anthrotype** [comment]
I'd also like to know what's the status of this issue. @simoncozens earlier said he could repro and that the problem was 'in the "minimal" build idea.'
Maybe the title of the issue is perhaps too broad and should be renamed to narrow it down a bit?

**Comment by simoncozens** [comment]
Sorry, I'll try and take another look at this tomorrow. Obviously I thought I had fixed it. I suspect there's another issue that I haven't cracked. @RosaWagner is League Spartan still a good test case? Or shall I look at building Work Sans?

**Comment by RosaWagner** [comment]
We probably fixed the layer names, but I see an attachment to my first comment, it is probably the buggy version

**Comment by emmamarichal** [comment]
I think it was about Playfair Display, that has on some letters, 3 values in the brace layers
https://github.com/clauseggers/Playfair

<img width="293" alt="Capture d’écran 2022-08-31 à 16 10 17" src="https://user-images.githubusercontent.com/64773544/187699425-2f122300-22f3-485b-891f-3d3da9681472.png">

**Comment by simoncozens** [comment]
I think with the current architecture it is very difficult to support alternate layers with both start and end stops.

**Comment by emmamarichal** [comment]
Hello, 
I wanted to do a small "tutorial" to solve an issue I met.

1) The original file was like this
<img width="185" alt="Capture d’écran 2022-10-21 à 17 42 33" src="https://user-images.githubusercontent.com/64773544/197235770-958320d1-ddee-4cdc-b2cc-33e0643b8196.png">
2) To get the good way of writing this, I did "+" to add them as Alternates layers
<img width="184" alt="Capture d’écran 2022-10-21 à 17 42 41" src="https://user-images.githubusercontent.com/64773544/197235773-c5377aa0-0781-48e1-b515-e733d898b872.png">
3) At the end, we get this, that is the good structure to have.
<img width="178" alt="Capture d’écran 2022-10-21 à 17 42 55" src="https://user-images.githubusercontent.com/64773544/197235777-76e08690-1e02-4d59-8f7b-f5c7feab1ee8.png">

But it didn't export properly and I got this error: 
`TypeError: '<=' not supported between instances of 'int' and 'str'`

To avoid that:
- Save the drawing of your layers somewhere
1) Start with your 2 masters
<img width="180" alt="Capture d’écran 2022-10-21 à 17 49 24" src="https://user-images.githubusercontent.com/64773544/197237142-a4368767-ac1d-4cd1-8448-4a77c007118d.png">
2) Add a layer with "+"
<img width="181" alt="Capture d’écran 2022-10-21 à 17 49 31" src="https://user-images.githubusercontent.com/64773544/197237144-5674b167-3206-4537-a18d-b4c8305813ad.png">
3) Right clic on it, select "Alternate"
<img width="281" alt="Capture d’écran 2022-10-21 à 17 49 37" src="https://user-images.githubusercontent.com/64773544/197237147-e9f70dd6-a248-48c2-afac-c1afc056b555.png">
4) Fill with your values
<img width="563" alt="Capture d’écran 2022-10-21 à 17 49 47" src="https://user-images.githubusercontent.com/64773544/197237148-cac91c35-c3bd-4eb8-a4cb-3489eaf605a5.png">
5) Then you have the same result, but with another process, and it works!
<img width="183" alt="Capture d’écran 2022-10-21 à 17 50 03" src="https://user-images.githubusercontent.com/64773544/197237152-2d34579a-fa54-490f-b409-2e4902d764e5.png">

I hope it will help if someone has the same kind of issue!

**Comment by schriftgestalt** [comment]
In the file from the first part, can you right click the default layer in the layer panel and see if the 'Alternate' is still checked? If so, uncheck it. Otherwise, can you send me that file?

**Comment by schriftgestalt** [comment]
You can also do it like this (at least Glyphs supports it like this):
<img width="189" alt="Screen Shot 2022-10-25 at 10 33 25" src="https://user-images.githubusercontent.com/174660/197725146-e52f86dc-84ca-49f5-ad59-5cc1d6cfdd16.png">
(the `Light and the `[]` master are compatible/interpolating (full stroke) and the `[550<wg]` and `Bold [550<wg]` are compatible (two small strokes at the top and bottom).)

The advantage is that in the font view, the Bold master looks good as it has the alternate shape.

**Comment by schriftgestalt** [comment]
One thing that might cause the error is that the values in the "axisRules" settings in the layers are stored as string. So it might need an `int()` in the right place. (or `float()`, of course).

**Comment by weiweihuanghuang** [comment]
Thanks @simoncozens!

**Comment by emmamarichal** [comment]
Hi @simoncozens,
I'm working on Playfair, I managed to export the upright well, even with the complex alternates layers (https://github.com/googlefonts/glyphsLib/issues/741#issuecomment-1232992617)

However, I have this error for the italics, I think it has to do with some ligatures (pink glyphs in the sources). I'm on it since yesterday, I can't seem to solve it. Do you have any idea where this problem is coming from?

```
Lib/featureVars.py", line 168, in overlayFeatureVariations
    intersection, remainder = overlayBox(currBox, box)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/featureVars.py", line 222, in overlayBox
    minimum = max(min1, min2)
TypeError: '>' not supported between instances of 'int' and 'str'
```

Repo: https://github.com/emmamarichal/Playfair/blob/master/sources/Playfair-Italic.glyphs

Thanks!

**Comment by simoncozens** [comment]
That shouldn't happen! I'll have a look.

**Comment by simoncozens** [comment]
OK, I've fixed the presenting problem, but there is still something not quite right here as the font is now failing compatibility checking; the layers look fine in Glyphs, but maybe when we work out the alternates one of layers has ended up in the wrong conditionset or something like that.

**Comment by emmamarichal** [comment]
Ok great, I'll take a look, thanks a lot!

**Comment by simoncozens** [comment]
I've found it. One of the layers does not have a name, so it is getting lost. But I am not sure bracket layers need to have names, since w make our own magic names for them.

**Comment by emmamarichal** [comment]
In which glyphs do you see that? I can't find it

**Comment by simoncozens** [comment]
You can't see it because Glyphs hides the user-supplied names of alternate layers and replaces them with the description of the conditions - so you see "[5<oz<410,80<wd<150]" but actually internally the layer is called "30 Jan 22, 11:43" or something like that. And because of that you can't easily fix it in the UI. (You can fix it with scripting, I suppose.)

So we should fix it by not skipping anonymous alternate layers.

**Comment by emmamarichal** [comment]
Aah ok I see, yes indeed we often had this problem.Thanks!

**Comment by schriftgestalt** [comment]
For Glyphs 3 source, the layer names have no meaning any more and should be ignored.
