### ISSUE TITLE
Multiaxis v3 Glyphs files fail to generate multiaxis designspace

### ISSUE THREAD

**Issue by jpt** [googlefonts/glyphsLib#746]
The error message suggests that glyphsLib is only looking at weight and width; the test font contains an optical axis, so the locations are unique

```
glyphs2ufo TestFont.glyphs
DesignSpace sources contain duplicate locations; varLib expects each master to define a unique location.
  ['Test Font Thin 8pt', 'Test Font Bold 8pt', 'Test Font Thin 144pt', 'Test Font Bold 144pt', 'Test Font Thin 8pt Expanded', 'Test Font Bold 8pt Expanded', 'Test Font Thin 144pt Expanded', 'Test Font Bold 144pt Expanded'] => {'Weight': 100, 'Width': 100, 'Custom': 0}
```

**Comment by jpt** [comment]
FWIW, if I resave as a v2 file, it works fine.

I've attached the minimally mastered test font (one glyph - `n`) that I've been using to evaluate glyphsLib. It's reflective of font that properly compiles using Glyphs 3.0.4 build 3100

[TestFont.glyphs.zip](https://github.com/googlefonts/glyphsLib/files/7491263/TestFont.glyphs.zip)

**Comment by simoncozens** [comment]
As of the PR above, glyphs2ufo completes successfully but gives an ambiguous designspace file because of #745. So I am closing this and moving there instead.
