### ISSUE TITLE
Backup brace layers are treated as brace layers in v3 files

### ISSUE THREAD

**Issue by jpt** [googlefonts/glyphsLib#747]
Glyphs v3 relies on some extra `attributes.coordinates` metadata for brace layers (now called intermediate masters). They are not defined by the name of the layer itself.

e.g. through the Glyphs scripting API itself, if you want to find brace layers nowadays:

```
font = Glyphs.font
def printBraceLayers(font):
	for glyph in font.glyphs:
		for layer in glyph.layers:
			if layer.isSpecialLayer and layer.attributes['coordinates']:
				print(layer.name)
printBraceLayers(font)
```

Whereas a *lot* of existing tooling for Glyphs (seemingly including glyphsLib) relies more on this approach:

```
font = Glyphs.font
def printBraceLayers(font):
	for glyph in font.glyphs:
		for layer in glyph.layers:
			if "{" in layer.name:
				print(layer.name)
printBraceLayers(font)
```

The big problem with this is that actual internal layer name can be anything not just `{coord, coord, coord, ...}` now. And that backup layers — copies that contain `{` in them — can trigger warnings, as glyphsLib does:

In a font with a legitimate `Intermediate Master` layer at `{35, 72, 125}` if there is a backup layer with a date appended - `{30, 72, 125} Nov 6, 21, 14:48` in this case - but is not explicitly set to be an Intermediate Master (does not have  coordinate attributes), it still triggers anything looking for brace layers by name rather than those coordinates. From glyphsLib:

 `Glyph(s) ['n'], brace layer '{30, 72, 125} Nov 6, 21, 14:48' defines more locations than there are design axes.`

^ when that layer is not, according to Glyphs anymore, a brace layer

**Comment by khaledhosny** [comment]
This happens with color layers too. I think we should make the builder code check for layer attributes, and for G2 fonts emulate layer attributes by checking for layer names.
