### ISSUE TITLE
Every .glyphs file created with FontLab 7 displays syntax error, making it impossible to even start compiling it with Fontmake

### ISSUE THREAD

**Issue by cssobral2013** [googlefonts/glyphsLib#760]
Output:
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "manrope-italic.glyphs" file into <GSFont>
fontmake: Error: In 'manrope-italic.glyphs': Loading Glyphs file failed: Missing ';' on line 50664

**Comment by khaledhosny** [comment]
https://forum.fontlab.com/fontlab-7/glyphs-files-exported-from-fontlab-cant-be-opened-in-glyphs-3/
https://forum.glyphsapp.com/t/glyphs-file-exported-from-fontlab-7-can-t-be-opened-in-glyphs-3/20712
