### ISSUE TITLE
Width of intermediate layer written to UFO is wrong

### ISSUE THREAD

**Issue by yanone** [googlefonts/glyphsLib#773]
The master layer’s width gets written instead. Outlines and anchors are okay, tho.

Please see attached minimal font. The file `OodleSans.Regular.ufo/glyphs.10. F_eb. 22, 08_39/hah-ar.init.swsh.glif` has width `1545` (same as its master layer) but should be `1045`.

I tried digging into the code but couldn't find it. I used the normal `fontmake -g sources/IntermediateLayerWidth.glyphs -o ufo` to convert.

[IntermediateLayerWidth.glyphs.zip](https://github.com/googlefonts/glyphsLib/files/8039131/IntermediateLayerWidth.glyphs.zip)

**Comment by anthrotype** [comment]
somewhere here must be the hiding the bug:

https://github.com/googlefonts/glyphsLib/blob/57e66d21b71676a4e05b6ab02cb6204aad0ef81a/Lib/glyphsLib/builder/glyph.py#L254-L278

**Comment by anthrotype** [comment]
regression probably introduced with this https://github.com/googlefonts/glyphsLib/pull/641

I think line 267 of glyphsLib/builder/glyph.py should be:

```diff
-      width = None 
+      width = layer.width 
```

@yanone can you try if that fixes it and send a PR if so? thanks

**Comment by yanone** [comment]
I fixed it (see linked PR). The local tests run fine, only the regression test throws an error. Please help me make sense of it. I almost feel like thats expected now, because fonts have shipped with wrong layer widths since April 2021 now.
