### ISSUE TITLE
wrong usWeightClass in static ttf

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/glyphsLib#776]
Trying to export static ttf with fontmake, and usWeightClass is 400 everywhere.
If I use builder the usWeightClass is correct, so I guess the builder is fixing it in post-process.

**Comment by m4rc1e** [comment]
Can you share the source please?

**Comment by RosaWagner** [comment]
Ah wait I am testing something else, I think fontmake is exporting the masters and not the instances, cause the masters are incompatible

**Comment by RosaWagner** [comment]
Yes, so I think it's a Fontmake issue cause I am trying to replicate with Texturina and results are weird: somehow it only exports the masters and not the instances, and so the weightClass is not set.

On the other side, builder export all the instances, but only if the masters are compatible. And the thing is is that we try to build static instances from masters that are not compatible (but we have only the instances from the masters), and builder is raising interpolation error.

**Comment by RosaWagner** [comment]
This is our WIP repo:
https://github.com/emmamarichal/Crimson/tree/495b071bbe63c7bbe48cae1439b6e13d43df8e4f

**Comment by RosaWagner** [comment]
I close this since it's a fontmake issue
