### ISSUE TITLE
Support .glyphspackage format

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/glyphsLib#801]
_This was briefly mentioned at https://github.com/googlefonts/glyphsLib/issues/643, but needs a separate issue. Here it is!_

I've recently learned about the new-ish `.glyphspackage` file format for GlyphsApp, which saves Glyphs projects in a way that is much better for Git version control. It also apparently is helpful in projects with many glyphs, such as CJK projects (perhaps partly because it helps with Git collaboration?)

In a `.glyphspackage`, each glyph gets its own file, and the package also contains one file for "fontinfo" (metadata, kerning, features, etc), and one file for glyph order. Maybe other files are created where needed.

This makes it much more feasible to collaborate on Glyphs projects via Git, so it would be awesome if glyphsLib were to support these for builds. As it is, I think I may have to open the package in GlyphsApp, then manually "save as" to convert to a .glyphs file for building. This isn't horrible, but isn't as nice as a fully scripted build!

Unfortunately, I am having a hard time finding much documentation on the format on the Glyphs site, and that might be an issue for supporting it here.

The main references are on the forum, like this: https://forum.glyphsapp.com/t/are-glyphspackage-stable/16744. 

Also related: https://github.com/googlefonts/fontmake/issues/923

Maybe @schriftgestalt could give more insight into this?

Thanks!

**Comment by anthrotype** [comment]
yes, would be nice to support that.

@simoncozens posted a snippet from babelfont that reads that using openstep_plist, could be a start: https://github.com/googlefonts/glyphsLib/pull/652#issuecomment-801003197

**Comment by arrowtype** [comment]
One very helpful thing in the near term, for users: https://github.com/jenskutilek/glyphspkg!

This may be a stupid question, but could that library perhaps be used as a requirement for glyphsLib, and this problem could be solved quite quickly? Or, would it be better to re-write the functionality from scratch?

**Comment by khaledhosny** [comment]
If you use something like Makefile or a build script, you can use https://github.com/jenskutilek/glyphspkg to convert to a single .glyphs file and pass this to fontmake.

**Comment by anthrotype** [comment]
from skimming through `glyphspkg`, it seems pretty basic (see `package_to_single` function here: https://github.com/jenskutilek/glyphspkg/blob/65b3f2415dd6964a90e75674a32cf7c6f0c57921/Lib/glyphspkg/package_to_single.py#L7), I think it should be straightforward to integrate similar code in glyphsLib, just need someone/some time to actually do it. If @jenskutilek feels like contributing some of his code upstream, even better :)
I would prefer to not simply use as external dependency as is, it doesn't seem like it's designed for library use case, more like a CLI (e.g. uses `print` instead of logging).

**Comment by anthrotype** [comment]
it's curious that they are using the same UFO3's userNameToFileName algorithm to go from glyph names (found in the order.plist file) to the actual glyph _file_ names.

https://github.com/jenskutilek/glyphspkg/blob/main/Lib/glyphspkg/filenames.py#L40

**Comment by florianpircher** [comment]
> it's curious that they are using the same UFO3's userNameToFileName algorithm to go from glyph names (found in the order.plist file) to the actual glyph file names.

Glyph names are case sensitive while many file systems are not, so such a naming system is needed. And since UFO already has a common naming convention that is implemented in various software (including Glyphs), it’s reused for .glyphspackage.

**Comment by anthrotype** [comment]
Of course, I don't see a problem with that.

So, is there are any spec or docs that describe how this glyphspackage format works? Or did @jenskutilek simply reverse engineered it?

**Comment by florianpircher** [comment]
No, currently there is not. I outlined the differences between .glyphs and .glyphspackage quickly [on the forum](https://forum.glyphsapp.com/t/documentation-on-the-glyphspackage-format/23435/2) but I would be happy to write a short, official documentation (on the Glyphs website or maybe on the Glyphs SDK GitHub repository) that can be used as a reference for other implementations.

**Comment by anthrotype** [comment]
that would be awesome, thanks!

**Comment by schriftgestalt** [comment]
there is already some info about the .glyphsPackage format: https://github.com/schriftgestalt/GlyphsSDK/blob/Glyphs3/GlyphsFileFormat/GlyphsFileFormatv3.md#file-structure
So it might be best to discuss missing info in an issue in the GlyphsSDK repo.

**Comment by schriftgestalt** [comment]
And Glyphs uses the same algorithm to compute the names for .glyph file and for .glif files. I’ll have a look if it is up to date with the current ufo code.

**Comment by jenskutilek** [comment]
> from skimming through `glyphspkg`, it seems pretty basic (see `package_to_single` function here: https://github.com/jenskutilek/glyphspkg/blob/65b3f2415dd6964a90e75674a32cf7c6f0c57921/Lib/glyphspkg/package_to_single.py#L7), I think it should be straightforward to integrate similar code in glyphsLib, just need someone/some time to actually do it. If @jenskutilek feels like contributing some of his code upstream, even better :)

Basic support should be easy, but to support everything that currently can take a .glyphs file for .glyphspackage as well seems to be a fair amount of work. E.g. you can’t pass a file pointer around for a directory, is .glyphspackage also needed as an output format, for roundtripping, etc.?

I’m a bit wary of committing to doing this, I don’t have the time at the moment, and also I’ve been burned before when trying to contribute a large chunk of code ([TrueType instruction support for ufo2ft](https://github.com/googlefonts/ufo2ft/pull/577) basically sittiing unmerged for years) ...

But if anyone wants to take on this, feel free to do so. Making a separate utility was just the quickest way to get the job done for me (supporting glyphspackage in the Python font build toolchain).

> I would prefer to not simply use as external dependency as is, it doesn't seem like it's designed for library use case, more like a CLI (e.g. uses `print` instead of logging).

I’ve just [published an update](https://pypi.org/project/glyphspkg/0.1.7/) that uses logging, along with some bugfixes.

**Comment by schriftgestalt** [comment]
The code that reads and writes the data is the same for .glyphs and .glyphspackage. Only called in different order. With the right code structure it should be quite easy. 
Reading the fontinfo.plist can be done with the same code that read the .glyphs file.
The .glyph files contain the exact same structure then the items in the `glyphs = ()` part of the .glyphs file. After all .glyph files are read, sort the glyphs by the order from the order.plist.

**Comment by simoncozens** [comment]
I'm going to take this on. It isn't particularly difficult, I just need to get around to it. I'll try and take a look this week.

**Comment by schriftgestalt** [comment]
Thanks.
