### ISSUE TITLE
Can't generate font >> invalid literal for int() with base 10: 'bit 29'

### ISSUE THREAD

**Issue by etunni** [googlefonts/glyphsLib#807]
Loading Glyphs file failed: invalid literal for int() with base 10: 'bit 29'

**Comment by etunni** [comment]
I was able to generate the font files, finally.
The source files traveled from Glyphs 2 to G3 and back during the design process, perhaps some data in the windows: info / masters / export are incompatible between G2 and G3 and some wrong data still remaining in internal code.
I deleted and entered again the same data and the source was fixed

**Comment by guidoferreyra** [comment]
I get this erorr ver often when glyphs file has unicodeRanges and/or codepageRanges custom parameters

**Comment by anthrotype** [comment]
glyphsLib is trying to create an integer with base 10 from a string like int("bit 29"), which of course fails with ValueError. 

Can you search for the string "bit 29" in your source file and copy/paste it here with a few lines before and after for context?

I'd like to see where it shows up to understand where it's coming from, thanks

**Comment by guidoferreyra** [comment]
```
{
name = codePageRanges;
value = (
"1252",
"1250",
"1254",
"1257",
"bit 29"
);
```
"bit 29" corresponds to 
<img width="293" alt="imagen" src="https://user-images.githubusercontent.com/1755590/197017092-608a2411-b369-42b7-85cf-8be15133fbee.png">

**Comment by schriftgestalt** [comment]
The values in the codePageRanges are not numbers but strings. That are the names of the codepages. But some bits don’t have a names assigned but some people still set them.

**Comment by anthrotype** [comment]
closing as duplicate of https://github.com/googlefonts/glyphsLib/issues/530
