### ISSUE TITLE
Disabled custom parameters are treated as enabled

### ISSUE THREAD

**Issue by justinpenner** [googlefonts/glyphsLib#809]
Would it be possible to add/fix support for disabled custom parameters? It's handy to disable a custom parameter in Glyphs, but instead I have to delete the custom parameter if I want glyphsLib to ignore it.

After digging around in glyphsLib I can see that there seems to be partial support for it, but it isn't working properly. For example, if my .glyphs source contains:
```
customParameters = (
{
disabled = 1;
name = glyphOrder;
value = (
x,
y,
z
);
}
);
```

…then glyphsLib outputs a lib.plist containing:
```
<key>public.glyphOrder</key>
<array>
  <string>x</string>
  <string>y</string>
  <string>z</string>
</array>
```

And if I load the same .glyphs source as an object, I can see that `GSCustomParameter` does seem to have a `disabled` property, but the value is `False` when it should be `True`.
```
>>> vars(font._customParameters[0])
{'name': 'glyphOrder', '_value': ['x', 'y', 'z'], 'disabled': False}
```

**Comment by khaledhosny** [comment]
Duplicate pf #905
