### ISSUE TITLE
Alignment Zones / BlueValues missing when converting Glyphs3 → UFO?

### ISSUE THREAD

**Issue by rutherfordcraze** [googlefonts/glyphsLib#816]
Using `glyphsLib.build_masters` to convert a .glyphs file (Version 3) to UFO seems to ignore alignment zones; the resulting UFOs have no BlueValues.

I couldn’t see any indication that this data loss is expected, so I’m unclear on whether this is a bug or if there are still Glyphs v3 teething problems.

**Comment by kontur** [comment]
As mentioned in #754

**Comment by guidoferreyra** [comment]
+1 to this

**Comment by kontur** [comment]
This is fixed with the merged #825 and can be closed imo.
