### ISSUE TITLE
.glyphspackage name rules are slightly different to UFO rules

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/glyphsLib#846]
We currently use `fontTools.misc.filenames.userNameToFileName` to convert a glyph name to a filename when reading/writing glyphspackage files.

As well as adding underscores to make a distinction between capitals and lower case letters on case-folding filesystems, `userNameToFileName` also adds an underscore to the start of certain "reserved" file names (such as the MSDOS console device "con"). Glyphs 3 does not apply this reserved file names check, so a glyph called `con` (U+A76F LATIN SMALL LETTER CON) is stored by Glyphs 3 as `glyphs/con.glyph`. We turn it into `glyphs/_con.glyph` and then we don't find it.

**Comment by schriftgestalt** [comment]
I heard about those reserved names. Is that really still a problem? Specially if the file has an extension? If so Glyphs probably should add the extra underscores.

**Comment by anthrotype** [comment]
if simply adding the file extension makes reserved filenames no longer reserved.. why does ufoLib even bother escaping them? it also has adds a file extension .glif but still escapes.

**Comment by simoncozens** [comment]
This was fixed on the Glyphs end, in patchlevel 3169. If you can't load a .glyphspackage file in glyphsLib, please upgrade your version of Glyphs and save it again.

**Comment by schriftgestalt** [comment]
Glyphs before or after version 3169 should not have any problem opening a file with or without underscore. Saving in an older version might produce a duplicate of that file.

**Comment by simoncozens** [comment]
> This was fixed on the Glyphs end, in patchlevel 3169.

@schriftgestalt, there is still a problem here. Both Glyphs and `.misc.filenames.userNameToFileName` turn the `con` glyph into `_con.glyph`. However, Glyphs turns `Con` (capital con!) into `_C_on.glyph`. However, fontTools turns it into `C_on.glyph` (this makes sense, because once you have turned `Con` into `C_on` there is no Windows issue to avoid.)

So fontmake currently won't compile a file saved with Glyphs with a `Con` glyph, because it can't find it.

**Comment by schriftgestalt** [comment]
I’ll have a look. 

But was in really intended to load the .glif file based on the name? I thought that you should read all files and map them based of the name in the file?

**Comment by anthrotype** [comment]
> because it can't find it.

what does the contents.plist say? that's what ufoLib shoud use to locate the .glif file based on the glyph name.
