### ISSUE TITLE
quotes in xml header

### ISSUE THREAD

**Issue by schriftgestalt** [googlefonts/glyphsLib#852]
Is there a reason the first line (`<?xml version='1.0' encoding='UTF-8'?>`) is having single quotes where all other attributes (`<glyph name="A" format="2">`) use double quotes?

**Comment by anthrotype** [comment]
i suppose it's just the way our xml serialization library (lxml) does it. Does it matter?

**Comment by anthrotype** [comment]
here's a bit of history https://github.com/lxml/lxml/pull/277

**Comment by schriftgestalt** [comment]
I still think it should be changed. Having different quotes in one file is annoying. If I search for `<?xml version=` in my site-packages, I get 91 time double quotes and 8 single (most are ufo-test files in defcon and such). 

And the ufonormalizer is using double quotes, too.

It really needs a formatting guideline to avoid this meaningless diffs.

**Comment by anthrotype** [comment]
Both lxml and the built-in cpython ElementTree library used by fontTools.ufoLib when lxml is not available use single quotes for the xml header by default and do not allow to change it. Either single/double quotes are valid in xml so it doesn't really matter, it's meaningless like you said. Besides it is too late to make such a change, it would create spurious diffs in thousands of projects for no good reasons. If one wishes, they can use the ufonormalizer.
