### ISSUE TITLE
Add support for instance properties

### ISSUE THREAD

**Issue by IvanUkhov** [googlefonts/glyphsLib#861]
When opening and saving a Glyphs file, the `properties` section gets removed in each instance as illustrated below.

```diff
-properties = (
-{
-key = familyNames;
-values = (
-{
-language = dflt;
-value = "Proxima Nova ExCn";
-}
-);
-},
-{
-key = styleMapFamilyNames;
-values = (
-{
-language = dflt;
-value = "Proxima Nova ExCn Black";
-}
-);
-},
-{
-key = postscriptFontName;
-value = "ProximaNovaExCn-Black";
-},
-{
-key = preferredFamilyNames;
-values = (
-{
-language = dflt;
-value = "Proxima Nova Extra Condensed";
-}
-);
-}
-);
```

<img width="1381" alt="Skärmavbild 2023-02-20 kl  11 07 34" src="https://user-images.githubusercontent.com/57440/220078027-a8fcc93e-3aeb-4352-9f0d-4b36ad959624.png">

**Comment by anthrotype** [comment]
is this somehow related to https://github.com/googlefonts/glyphsLib/issues/860?

I'm not sure what 'instance properties' are, is this documented somewhere?

Would be nice to have support for these, of course. We just need somebody to volunteer :)

**Comment by IvanUkhov** [comment]
Yes, they seem to be related. This one is supposedly more general. Regarding “instance properties,” I called them that way because the key is called `properties`, and it is present in every dictionary in the `instances` list 😀

**Comment by anthrotype** [comment]
https://github.com/schriftgestalt/GlyphsSDK/blob/Glyphs3/GlyphsFileFormat/GlyphsFileFormatv3.md#properties

**Comment by IvanUkhov** [comment]
I have started to look around. Shouldn't this chunk added two years ago do just that?

https://github.com/googlefonts/glyphsLib/blob/main/Lib/glyphsLib/classes.py#L3421
https://github.com/googlefonts/glyphsLib/blob/main/Lib/glyphsLib/classes.py#L3117
