### ISSUE TITLE
Erroneous duplication of components in certain color layers of COLRv0 fonts

### ISSUE THREAD

**Issue by yanone** [googlefonts/glyphsLib#866]
Working on a Cairo Play COLRv0 update ([my fork here](https://github.com/yanone/Cairo)), I found that a handful of ligatures are painted red over an identical black outline. You can see a slight black bleed around the red shape:

<img width="161" alt="Bildschirm­foto 2023-02-24 um 11 46 31" src="https://user-images.githubusercontent.com/175386/221159910-d7dc7e8f-23b1-4ff2-93e4-48036530e2b5.png">

Most ligatures in question are based on the same shape (toothletter+noon), but one other shape is painted in purple, too. So by all accounts I need to describe the occurence as _seemingly random_. I couldn't see any pattern in the source that could explain why components in these glyphs are duplicated and in others not.

<img width="968" alt="Bildschirm­foto 2023-02-24 um 11 48 08" src="https://user-images.githubusercontent.com/175386/221160811-d03b888f-25f1-4d9a-b35d-9ebcc5c2adac.png">

Investigating the files I found that the intermediate UFOs show a total of two components in the `noon_noon-ar.fina.color1.glif` glyph which is supposed to only hold the red dot but now also holds the base component, too, a duplication of the component in the `.color0` glyph, or components being completely identical to the non-color glyph, whichever way you'd like to look at it.

```xml
<?xml version='1.0' encoding='UTF-8'?>
<glyph name="noon_noon-ar.fina.color1" format="2">
  <advance width="993"/>
  <unicode hex="FC8D"/>
  <outline>
    <component base="alefMaksura_noon-ar.fina"/>
    <component base="dotabove-ar" xOffset="787" yOffset="-20"/>
  </outline>
  <lib>
    <dict>
      <key>com.schriftgestaltung.Glyphs.ComponentInfo</key>
      <array>
        <dict>
          <key>anchor</key>
          <string>top_1</string>
          <key>index</key>
          <integer>1</integer>
          <key>name</key>
          <string>dotabove-ar</string>
        </dict>
      </array>
    </dict>
  </lib>
</glyph>
```

As always, I'm happy to assist any debugging.

**Comment by anthrotype** [comment]
cc @khaledhosny who implemented exports of COLRv0 layers in glyphsLib
