### ISSUE TITLE
Support other alternatives of specifying hints in format 3

### ISSUE THREAD

**Issue by IvanUkhov** [googlefonts/glyphsLib#868]
As @schriftgestalt mentioned in #864, the official reference file, `GlyphsFileFormatv3.glyphs`, has been updated to capture more. Currently, the library fails to parse the updated file. One of the reasons is that not all alternatives of specifying `origin`, `other1`, `other2`, and `target` in hints seem to be supported. In format 3, they are tuples with not only two but occasionally one, three, and four entries:

https://github.com/schriftgestalt/GlyphsSDK/blob/Glyphs3/GlyphsFileFormat/GlyphsFileFormatv3.md

**Comment by anthrotype** [comment]
possibly duplicate of https://github.com/googlefonts/glyphsLib/issues/817

**Comment by IvanUkhov** [comment]
Close due to #869.
