### ISSUE TITLE
Extracting source with brace layers fails on str to int comparison

### ISSUE THREAD

**Issue by kontur** [googlefonts/glyphsLib#892]
In a Glyphs source file in format 3 this line [https://github.com/googlefonts/glyphsLib/blob/d93c234f03a6b7452931151797ec8ec50227078e/Lib/glyphsLib/builder/sources.py#L208] fails with a:

> File "/Users/johannes/.pyenv/versions/3.10.4/envs/mrhandy/lib/python3.10/site-packages/glyphsLib/builder/sources.py", line 210, in _to_designspace_source_layer
    brace_layers.sort(key=lambda x: tuple(x.location.values()))
TypeError: '<' not supported between instances of 'str' and 'int'

When I add a `print(brace_layers)` before I get:

```
...
SourceDescriptor(
    filename='Foobar-CondensedBold.ufo',
    path=None,
    name='Foobar Condensed Bold {72, 200}',
    layerName='{72, 200}',
    location=OrderedDict([('Weight', 72), ('Width', 200)]),
    copyLib=False,
    copyGroups=False,
    copyFeatures=False,
    muteKerning=False,
    muteInfo=False,
    mutedGlyphNames=[],
    familyName=None,
    styleName=None,
    localisedFamilyName={},
), SourceDescriptor(
    filename='Foobar-CondensedBold.ufo',
    path=None,
    name='Foobar Condensed Bold {22, 100}',
    layerName='{22, 100}',
    location=OrderedDict([('Weight', '22'), ('Width', '100')]),
    copyLib=False,
    copyGroups=False,
    copyFeatures=False,
    muteKerning=False,
    muteInfo=False,
    mutedGlyphNames=[],
    familyName=None,
    styleName=None,
    localisedFamilyName={},
),
...
```

Note how some locations are extracted as dicts with numeric values, and others as dicts with string values:

```
    layerName='{72, 200}',
    location=OrderedDict([('Weight', 72), ('Width', 200)]),
```
vs.
```
    layerName='{22, 100}',
    location=OrderedDict([('Weight', '22'), ('Width', '100')]),
```

Looking at the brace layer names in Glyphs I haven't been able to find what would cause this difference in interpreting the value as string vs int.

**Comment by kontur** [comment]
Printing the return from [this line](https://github.com/googlefonts/glyphsLib/blob/b845089b1822a53cd81bd351767281ab1ff7b07e/Lib/glyphsLib/classes.py#L3983) gives me:

```
...
BRACE COORDS [152, 100]
BRACE COORDS [152, 200]
BRACE COORDS ['22', '100']
BRACE COORDS ['152', '100']
BRACE COORDS ['152', '200']
BRACE COORDS [22, 100]
BRACE COORDS [152, 100]
...
```

Maybe this is an issue with a file that was upgraded from file version 2 to version 3 or something like that. Either way, the `return self.attributes["coordinates"]  # Glyphs 3` probably needs to undergo some coercion to be a tuple of int's. 

I can send a fix for that applied in that spot, but it would be interesting to know how strings end up there in the first place, e.g. is this an inconsistency in Glyphs itself or does this happen somewhere in the extraction.

**Comment by kontur** [comment]
(This isn't the place, but from a library user point of view, glyphsLib has basically degraded to alpha quality 😞 )

**Comment by anthrotype** [comment]
> Maybe this is an issue with a file that was upgraded from file version 2 to version 3 or something like that

indeed, maybe, but without looking at the actual file it's hard to tell

**Comment by kontur** [comment]
I've done a text check in the source file and all the layer `coordinates` look to be int's.

Checking the file layer names in Glyph with this macro:

```
for g in Glyphs.font.glyphs:
	for l in g.layers:
		if not l.isMasterLayer:
			print(l.name)
```

I also only get "int-looking" layer names; I suppose it is that layer name that is getting parsed for those value, not some other attribute(?).
> {22, 100}
{152, 100}
{22, 200}
{152, 200}
{22, 100}
...

This also confirmed there isn't any other non-master layers like backups or empty layer names or layer names with quotes or anything like that in the file.

**Comment by anthrotype** [comment]
> I suppose it is that layer name that is getting parsed for those value

no, if this is a Glyphs v3 source, then the brace layer coordinates are in the layer.attributes["coordinates"], the name is irrelevant

**Comment by anthrotype** [comment]
> all the layer coordinates look to be int's

**Comment by anthrotype** [comment]
> all the layer coordinates look to be int's

did you check the type of the coordinates values or just printed them? Because as you know, both `1` and `'1'` print() the same, their repr() will be different.

**Comment by kontur** [comment]
I consider this fixed with the merged PR.
