### ISSUE TITLE
Add support for custom parameters in variable instances

### ISSUE THREAD

**Issue by IvanUkhov** [googlefonts/glyphsLib#938]
Custom parameters in variable instances seem to be ignore upon compilation. The use case is to be able to have custom entries in the naming table in the resulting variable font.

I would appreciate a confirmation that it is indeed the case and that glyphsLib is the right place to tackle this problem.

Thank you!

**Comment by anthrotype** [comment]
Thanks

> glyphsLib is the right place to tackle this problem.

yes it is. Can you work on this?

Support for variable export settings is lacking at the moment, I think we only have some logic to ignore them when converting Glyphs.app instances to Designspace instance elements and that's it. /cc @jenskutilek

**Comment by khaledhosny** [comment]
But where to export these variable instances in DS? GSv5 `<variable-font>`? It does not seem to have any of `<instance>` attributes except `name` and `filename`, or should we put everything in its `<lib>`?

Should ufo2ft get support for it as well?

Looking again into [`<variable-font>`](https://fonttools.readthedocs.io/en/latest/designspaceLib/xml.html#variable-font-element), I’m not sure it is the same thing. It seems like it is only for creating subsets of the design space.

**Comment by khaledhosny** [comment]
I’m asking about `<variable-font>` on https://github.com/fonttools/fonttools/issues/3272, because it seems a more general DesignSpace issue.

**Comment by khaledhosny** [comment]
Fixed with #977
