### ISSUE TITLE
Problem with calt feature, wrong with fontmake, correct with Glyphs

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/glyphsLib#945]
source are in this branch: https://github.com/RosaWagner/Borel/tree/vietnamese/Borel/sources

The `calt` feature seems broken for some glyphs only when exporting with fontmake. 
I don't think my `calt` feature is wrong since GlyphsApp compiles it correctly. It seems to affect only the glyphs with multiple top accents (which are also the last ones that I added).

cc @simoncozens @schriftgestalt 

**Building with GlyphsApp:**
<img width="944" alt="Screenshot 2023-09-15 at 18 38 13" src="https://github.com/googlefonts/glyphsLib/assets/12222436/056cdbd5-f8a2-4241-bc2b-3066ac2a451b">

**Building with Fontmake:**
<img width="948" alt="Screenshot 2023-09-15 at 18 37 43" src="https://github.com/googlefonts/glyphsLib/assets/12222436/af6d98b9-370c-4861-9510-093737eec364">

**The calt feature:**

```
# All base lowercases letters (has unicode + idotaccent), would like to use a token but 
that one is not supported by GliphsLib

@Medial=[a aacute abreve abreveacute abrevedotbelow abrevegrave 
abrevehookabove abrevetilde acircumflex acircumflexacute 
acircumflexdotbelow acircumflexgrave acircumflexhookabove acircumflextilde 
adieresis adotbelow agrave ahookabove atilde ae b c ccedilla d dcroat e eacute 
ecircumflex ecircumflexacute ecircumflexdotbelow ecircumflexgrave 
ecircumflexhookabove ecircumflextilde edieresis edotbelow egrave 
ehookabove etilde f g gbreve h i idotless iacute icircumflex idieresis idotaccent 
idotbelow igrave ihookabove itilde j jdotless k l m n ntilde o oacute ocircumflex 
ocircumflexacute ocircumflexdotbelow ocircumflexgrave ocircumflexhookabove 
ocircumflextilde odieresis odotbelow ograve ohookabove ohorn ohornacute 
ohorndotbelow ohorngrave ohornhookabove ohorntilde otilde oe p q r s 
scedilla germandbls t u uacute ucircumflex udieresis udotbelow ugrave 
uhookabove uhorn uhornacute uhorndotbelow uhorngrave uhornhookabove 
uhorntilde utilde v w x y yacute ydotbelow ygrave yhookabove ytilde z]; 

@Isolated=[$[name endswith ".isol"]];

@Initial=[$[name endswith ".init"]];

@Final=[$[name endswith ".fina"]];

# Letters that need a long connection on the base line
@Base=[e $[name beginswith "e."] $[name beginswith "eacute"] $[name beginswith "ecircumflex"] 
$[name beginswith "edieresis"] $[name beginswith "edotbelow"] $[name beginswith "egrave"] 
$[name beginswith "ehookabove"] $[name beginswith "etilde"] oe $[name beginswith "oe."] 
ae $[name beginswith "ae."] c $[name beginswith "c."] $[name beginswith "ccedilla"] 
l $[name beginswith "l."] s $[name beginswith "s."] $[name beginswith "scedilla"] 
$[name beginswith "germandbls"] x $[name beginswith "x."]];

@BaseMedial=[$[name endswith ".medi.cv01"]];

@BaseFinal=[$[name endswith ".fina.cv01"]];

# Letters that needs connection from the top
@Top=[b $[name beginswith "b."] o $[name beginswith "o."] $[name beginswith "oacute"] 
$[name beginswith "ocircumflex"] $[name beginswith "odieresis"] $[name beginswith "odotbelow"] 
$[name beginswith "ograve"] $[name beginswith "ohookabove"] $[name beginswith "ohorn"] 
$[name beginswith "otilde"] v $[name beginswith "v."] w $[name beginswith "w."]];

@TopMedial=[$[name endswith ".medi.cv02"]];

@TopFinal=[$[name endswith ".fina.cv02"]];

# Letters that needs connection from the bottom
@Bottom=[j $[name beginswith "j."] $[name beginswith "jdotless"] g $[name beginswith "g."] 
$[name beginswith "gbreve"] q $[name beginswith "q."] y $[name beginswith "y."] 
$[name beginswith "yacute"] $[name beginswith "ydotbelow"] $[name beginswith "ygrave"] 
$[name beginswith "yhookabove"] $[name beginswith "ytilde"] z $[name beginswith "z."]];

@BottomMedial=[$[name endswith ".medi.cv03"]];

@BottomFinal=[$[name endswith ".fina.cv03"]];

lookup ISOLATED {
	lookupflag IgnoreMarks;
	ignore sub @Medial' @Lowercase, @Lowercase @Medial';
	sub @Medial' by @Isolated;
} ISOLATED;

lookup INITIAL {
	lookupflag IgnoreMarks;
	ignore sub @Lowercase @Medial';
	sub @Medial' by @Initial;
} INITIAL;

lookup FINAL {
	lookupflag IgnoreMarks;
	ignore sub @Medial' @Lowercase;
	sub @Base @Medial' by @BaseFinal;
	sub @Top @Medial' by @TopFinal;
	sub @Bottom @Medial' by @BottomFinal;
	sub @Medial' by @Final;
} FINAL;	

lookup MEDIAL {
	lookupflag IgnoreMarks;
	sub @Base @Medial' by @BaseMedial;
	sub @Top @Medial' by @TopMedial;
	sub @Bottom @Medial' by @BottomMedial;
} MEDIAL;

```

**Comment by schriftgestalt** [comment]
can you compare the GDEF mark class of the two fonts? it seems to happen when there are two marks on top, maybe the font uses a alternate mark and those are defined as mark in GDEF?

**Comment by RosaWagner** [comment]
precision: if I type `a` + `circumflexcomb_acutecomb`, it works fine, but calling the codepoint `acircumflexacute` directly doesn't.

**Comment by khaledhosny** [comment]
Where are you testing this? Do you get the issue in a specific app? You can try to debug the failing sequences with https://www.corvelsoftware.co.uk/crowbar/ and see what it does with the two fonts.

**Comment by anthrotype** [comment]
different GDEF GlyphClassDefs groups (specifically the one that defines mark glyphs) may be the culprit, the `lookupflag IgnoreMarks` uses those to decide whether to skip over the intervening mark glyphs and apply the substitutions as if the marks weren't there; if not ignored, an intervening glyph may break the substitution.

Have you dumped the `--debug-feature-file <file>` to inspect the features (including autogenerated ones) that fontmake compiles?

**Comment by RosaWagner** [comment]
@khaledhosny thanks for helping. I have this issue in Indesign, but the same is happening in Crowbar.
@anthrotype gonna try that now

The 2 files are there:
[Borel.zip](https://github.com/googlefonts/glyphsLib/files/12658290/Borel.zip)

**Comment by RosaWagner** [comment]
> Have you dumped the --debug-feature-file <file> to inspect the features (including autogenerated ones) that fontmake compiles?

@anthrotype either i am using the command in the wrong way or it doesn't find anything problematic. I have the lookupflag IgnoreMarks, you say it is ignoring only one mark and not 2?

**Comment by anthrotype** [comment]
> either i am using the command in the wrong way...

did you see a new debug feature file generated at the desired path?

The lookupflag IgnoreMarks is fine, I was trying to say the definition of what glyph is or is not a mark comes from the GDEF [GlyphCassDefs](http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#9.b), which defines four groups, in this order: base, ligature, marks and (ligature) components. I think you want to make sure that the third group that pertains to mark glyphs is identical in both the Glyphs.app generated features and in fontmake's (i.e. no glyph that is defined as "mark" by Glyphs is not also defined as such by fontmake).

Then you may want to make sure that the feature tokens as expanded by glyphsLib are the same as those from Glyphs.app, I think you should be able to inspect the latter's feature file in the ~/Application Support/Glyphs/Temp directory if I remeber correctly (cc @schriftgestalt).

**Comment by RosaWagner** [comment]
> did you see a new debug feature file generated at the desired path?
It was empty but now it is working somehow. markClass has the same number of lines.


Funnily enough, adding `sub acircumflexacute by a circumflexcomb_acutecomb;` in the `ccmp` feature fixes the issue on the web, but not in Indesign.

**Comment by schriftgestalt** [comment]
indesign doesn't do one to many substitutions in the default composer. In the paragraph settings, you can switch to the "World Ready composer". Then that sub will work.

But that this works may point to the actual problem. Is there acircumflexacute medi or final alternate?

**Comment by RosaWagner** [comment]
@schriftgestalt yep, there is the same number of alternates for each letters

**Comment by RosaWagner** [comment]
But not only the double accented letters are affected; also letters with `horn`, `hookabovecomb`, `etilde`, `itilde`, `dcroat`. 

Do we agree that there is a bug somewhere in glyphslib/fontmake that needs to get fixed?

**Comment by RosaWagner** [comment]
I update and compile everytime :/

**Comment by khaledhosny** [comment]
I downloaded the glyphs file, built with fontmake and got a broken font, updated and built again and the font is working:
<img width="805" alt="image" src="https://github.com/googlefonts/glyphsLib/assets/93914/e842b63d-bcfb-4895-8460-4ff3732fd249">

**Comment by RosaWagner** [comment]
@khaledhosny I updated the classes manually and it works, thanks. 
@schriftgestalt the update button doesn't update the "automatic" classes. Closing this issue and opening one in GlyphsApp's forum.
