### ISSUE TITLE
New problems with duplicate Unicode for color glyphs

### ISSUE THREAD

**Issue by yanone** [googlefonts/glyphsLib#946]
The duplicate Unicode issue still appears for [Blaka Ink](https://github.com/Gue3bara/Blaka/blob/master/sources/Blaka-Ink.glyphs), a COLRv1 font with gradients.

Observations:
* The tests that were [recently added](https://github.com/googlefonts/glyphsLib/pull/939/files) are clearly insufficient in catching this.
* I'm not 100% sure yet, but I believe that the unicodes must be muted in two places: [here](https://github.com/googlefonts/glyphsLib/blob/8c0157e4fba7a97fc9fbd4e4b532bcf92796c06f/Lib/glyphsLib/builder/color_layers.py#L197) in addition to [here](https://github.com/googlefonts/glyphsLib/blob/8c0157e4fba7a97fc9fbd4e4b532bcf92796c06f/Lib/glyphsLib/builder/color_layers.py#L42).
* [This condition](https://github.com/googlefonts/glyphsLib/blob/8c0157e4fba7a97fc9fbd4e4b532bcf92796c06f/Lib/glyphsLib/builder/glyph.py#L272) as triggered from [here](https://github.com/googlefonts/glyphsLib/blob/8c0157e4fba7a97fc9fbd4e4b532bcf92796c06f/Lib/glyphsLib/builder/builders.py#L34) currently prevents the processing of color layers for my font (`minimal=False`).

I can't easily fix this because I don't understand the _minimal_ architecture. But I'm happy to help with a PR if I'm told what to do.

**Comment by yanone** [comment]
I would start by adding

```python
    color0.attributes["color"] = 1
    color1.attributes["color"] = 1
```

to the new test [here](https://github.com/googlefonts/glyphsLib/blob/8c0157e4fba7a97fc9fbd4e4b532bcf92796c06f/tests/builder/builder_test.py#L1200).

It already starts throwing other errors before even checking for the unicodes.

**Comment by anthrotype** [comment]
> _clearly_ insufficient

well, not clearly enough to me by just reading this issue. Could you provide steps to reproduce the issue?

**Comment by anthrotype** [comment]
> I don't understand the minimal architecture. 

fontmake sets minimal=True because it's only interested in the minimal pieces of data required for compilation, not caring about other metadata desirable when roundtripping Glyphs<=>UFO

**Comment by yanone** [comment]
Take Blaka Ink (linked at the top), and try to generate a font from it.

It stalls with `fontmake: Error: In 'instance_ufo/BlakaInk-Regular.ufo': Compiling UFO failed: cannot map 'A.color0' to U+0041; already mapped to 'A'`, which is the same issue of https://github.com/googlefonts/glyphsLib/issues/937 still persisting.

I already pulled out all the relevant points in the code where something could go wrong.

**Comment by anthrotype** [comment]
https://github.com/googlefonts/glyphsLib/pull/939 was supposed to fix an issue with COLRv0 ("color palettes" fonts as Glyphs.app calls them). So you're saying the duplicate unicode issue also affects COLRv1, good. Will take a look

**Comment by yanone** [comment]
Then the test should be duplicated, once for COLRv0 and once for COLRv1. But given the absence of processing of any type of color glyphs through the minimal switch, even the COLRv0 must fail in real world examples, I believe.

**Comment by anthrotype** [comment]
> Then the test should be duplicated, once for COLRv0 and once for COLRv1

sounds good, can you work on a PR?

You're correct, we need to set unicodes to empty list right after we call to_ufo_glyph() to populate the COLRv1 layer glyph

**Comment by anthrotype** [comment]
I don't know what you mean with your references to minimal={True,False}, fontmake sets that correctly to True so the color layers _are_ processed. Are you doing something else?

**Comment by yanone** [comment]
> Are you doing something else?

Idk, I'm using `gftools builder`. Maybe it sets the variable. Let me investigate this.

I'll start a PR after lunch.

**Comment by yanone** [comment]
I don't understand this.

`gftools builder` doesn't set `minimal` to `False` anywhere, and in fact `fontmake` doesn't even have an interface for that. It calls `glyphsLib.to_designspace()` with `minimal=True` explicitly, as you said, so it overwrites the default `minimal=False` in the method definition of `glyphsLib.to_designspace()`, which in turn hands over the incoming parameter directly to `UFOBuilder()`.

In my case, both `to_designspace()` and `UFOBuilder()` receive a `minimal=False` value and thus fail the color handling.

I'm running `gftools builder sources/blakaink.yaml` in the [Blaka repo](https://github.com/Gue3bara/Blaka)

Can you please try to reproduce this? I feel like there's a ghost in my computer.

**Comment by anthrotype** [comment]
great so now we have a new fontmake-but-not-quite to bug fix

**Comment by yanone** [comment]
Turns out that the unicodes have to be explicitly muted for color layers as well, so I was hunting two different issues in two different packages, both leading up to the same error.

PR https://github.com/googlefonts/glyphsLib/pull/947 has the fix and a new test.
